/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.tools;
import dao.DaoUser;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import metier.Employeur;

/**
 *
 * @author paul
 */
public class FenetreAjoutEmployeur extends javax.swing.JFrame {
    private Employeur emp;
    Connection cnx;
    
    JFrame parent;
     private DaoUser daoEmployeur;
    /**
     * Creates new form FenetreAjoutEmployeur
     */
    public FenetreAjoutEmployeur(java.awt.Frame parent,Employeur emp,Connection cnx ) {
        initComponents();
        this.emp=emp;
        this.cnx=cnx;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitreAjouEmp = new javax.swing.JLabel();
        lNomEmp = new javax.swing.JLabel();
        txNomEmp = new javax.swing.JTextField();
        lAdresseEmp = new javax.swing.JLabel();
        txAdresseEmp = new javax.swing.JTextField();
        btEnejistrerEmp = new javax.swing.JButton();
        btAnnulerEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTitreAjouEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lTitreAjouEmp.setText("Ajout d'un nouvel employeur");

        lNomEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomEmp.setText("Nom");

        lAdresseEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lAdresseEmp.setText("Adresse");

        btEnejistrerEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btEnejistrerEmp.setText("Enregistrer");
        btEnejistrerEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnejistrerEmpActionPerformed(evt);
            }
        });

        btAnnulerEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAnnulerEmp.setText("Annuler");
        btAnnulerEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btAnnulerEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(187, 187, 187)
                            .addComponent(lTitreAjouEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lNomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lAdresseEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txNomEmp)
                                        .addComponent(txAdresseEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)))
                                .addComponent(btEnejistrerEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lTitreAjouEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lNomEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txNomEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txAdresseEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAnnulerEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEnejistrerEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lAdresseEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAnnulerEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerEmpActionPerformed
         this.dispose();
    }//GEN-LAST:event_btAnnulerEmpActionPerformed

    private void btEnejistrerEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnejistrerEmpActionPerformed
     try {

               int result;
                //int id_suppression = this.ens.getIdEnseignant();
                //bloc servant a recuperer les valeur dans les different fenetre
                emp.setNomEmployeur(this.txNomEmp.getText());
                emp.setAdresseEmployeur(this.txAdresseEmp.getText());
                //todo gestion employeur et ue
                
                //TODO: VALIDATION
               
                 CallableStatement cstmt = cnx.prepareCall ("{ ? = call AJOUTER_EMPLOYEUR (?,?)}");

                cstmt.registerOutParameter (1, Types.INTEGER);
                
                cstmt.setString(2,emp.getNomEmployeur());
                cstmt.setString(3,emp.getAdresseEmployeur());
                
               
                
                tools.debug(emp.toString());
                
                cstmt.execute();
                
                result = cstmt.getInt(1);

                tools.debug("Ajout : " + result);

                //if (result == 1) {

                    JOptionPane.showMessageDialog(null, "Ens "
                        +this.emp.getNomEmployeur()
                        + " a été bien ajouté",
                        "Information", JOptionPane.INFORMATION_MESSAGE);

                    //this.result = 1;

                    this.dispose();
                    
                /*
                } else {
                    //result != 1
                    throw new Exception("Impossible de supprimer ens");
                }*/

            } catch (SQLException ex) {
                Logger.getLogger(FenetreModifEnseignant.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FenetreModifEnseignant.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_btEnejistrerEmpActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnulerEmp;
    private javax.swing.JButton btEnejistrerEmp;
    private javax.swing.JLabel lAdresseEmp;
    private javax.swing.JLabel lNomEmp;
    private javax.swing.JLabel lTitreAjouEmp;
    private javax.swing.JTextField txAdresseEmp;
    private javax.swing.JTextField txNomEmp;
    // End of variables declaration//GEN-END:variables
}
