/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleCours;
import appli.ModeleGroupe;
import appli.ModeleSalle;
import appli.tools;
import dao.DaoAgenda;
import dao.DaoClasse;
import dao.DaoCours;
import dao.DaoGroupe;
import dao.DaoSalle;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import metier.CelluleAgenda;
import metier.Cours;
import metier.Salle;
import metier.Seance;
import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;


/**
 *
 * @author Mateusz
 */
public class FenetreModifSeance extends javax.swing.JDialog {
    
    int resultat;
    int id_seance;
    Connection cnx;
    
    DaoClasse dc;
    DaoAgenda da;
    DaoGroupe dg;
    DaoSalle ds;
    DaoCours dcr;
    
    ModeleGroupe mg;
    ModeleSalle ms;
    ModeleCours mc;
    
    Date seance_date;
    
    Seance currentSeance;
    
    int act;
    /**
     * 0 - ajout
     * 1 - modif    /**
     * 0 - ajout
     * 1 - modif
     */
    
    /**
     * Creates new form NewJDialog
     */
    public FenetreModifSeance(java.awt.Frame parent, CelluleAgenda seance, Connection cnx, int action) throws ParseException, SQLException {
        
       super(parent, true);
       initComponents();
        
       this.id_seance = seance.id_seance;
       this.cnx = cnx;
       this.resultat = 0;
       this.act = action;
       
       dc = new DaoClasse(cnx);
       da = new DaoAgenda(cnx);
       dg = new DaoGroupe(cnx);
       ds = new DaoSalle(cnx);
       dcr = new DaoCours(cnx);
       
       mg = new ModeleGroupe(dg);
       ms  = new ModeleSalle(ds);
       mc = new ModeleCours(dcr);
       
       cbSalle.setModel(ms);
       cbGroupe.setModel(mg);
       cbCours.setModel(mc);
       
       if (this.act == 0) {
           //ajout
           this.lTitre.setText("Ajout Seance");
           pValidationCours.setVisible(false);
           
       } else {
           //modif
           this.lTitre.setText("Modification Seance");
           //da.getSeanceUnique(currentSeance, id_seance);
           
           //this.cbClasse.setSelectedIndex(currentSeance.get));
       }
       
       SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");
       
       this.seance_date = seance.date;
       
       lDate.setText(df.format(seance.date));
       
       cbHeureDebut.setSelectedItem(tools.convertIntToHour(seance.heure));
       
       //3 heures par defaut
       cbHeureFin.setSelectedItem(tools.convertIntToHour(seance.heure+3));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCours = new javax.swing.JComboBox<>();
        lGroupe = new javax.swing.JLabel();
        cbHeureFin = new javax.swing.JComboBox<>();
        btAnnuler = new javax.swing.JButton();
        lHeureFin = new javax.swing.JLabel();
        lHeureDebut = new javax.swing.JLabel();
        lDate = new javax.swing.JLabel();
        lSalle = new javax.swing.JLabel();
        pValidationCours = new javax.swing.JPanel();
        rbValide = new javax.swing.JRadioButton();
        rbAnnule = new javax.swing.JRadioButton();
        lEnseignant = new javax.swing.JLabel();
        cbHeureDebut = new javax.swing.JComboBox<>();
        btValider = new javax.swing.JButton();
        cbGroupe = new javax.swing.JComboBox<>();
        cbSalle = new javax.swing.JComboBox<>();
        lTitre = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lGroupe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lGroupe.setText("Groupe");

        cbHeureFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00" }));

        btAnnuler.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        lHeureFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lHeureFin.setText("Heure de fin");

        lHeureDebut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lHeureDebut.setText("Heure de debut");

        lDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lDate.setText("Date");

        lSalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSalle.setText("Salle");

        pValidationCours.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Validation d'un cours", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        rbValide.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbValide.setText("  Cours ayant eu lieu");
        rbValide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbValideActionPerformed(evt);
            }
        });

        rbAnnule.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbAnnule.setText("  Cours annulé");

        javax.swing.GroupLayout pValidationCoursLayout = new javax.swing.GroupLayout(pValidationCours);
        pValidationCours.setLayout(pValidationCoursLayout);
        pValidationCoursLayout.setHorizontalGroup(
            pValidationCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pValidationCoursLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(rbValide, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbAnnule, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        pValidationCoursLayout.setVerticalGroup(
            pValidationCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pValidationCoursLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pValidationCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbValide)
                    .addComponent(rbAnnule))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        lEnseignant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lEnseignant.setText("Cours");

        cbHeureDebut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00" }));

        btValider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        cbGroupe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Groupe A" }));
        cbGroupe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGroupeItemStateChanged(evt);
            }
        });
        cbGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGroupeActionPerformed(evt);
            }
        });

        cbSalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4106" }));

        lTitre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lTitre.setText("Titre");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText(" Récurrence");
        jCheckBox1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btValider, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pValidationCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lTitre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lHeureDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbHeureDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lHeureFin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(cbHeureFin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 278, Short.MAX_VALUE))
                            .addComponent(cbCours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbGroupe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHeureDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHeureDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lHeureFin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHeureFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEnseignant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pValidationCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btValider, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int doModal() {
        this.setVisible(true);
        return resultat;
    }
    
    private void rbValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbValideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbValideActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        if (this.act == 0) {
            //creation
            
            int id_cours = mc.get(cbCours.getSelectedIndex()).getIdCours();
            int id_salle = ms.get(cbSalle.getSelectedIndex()).getIdSalle();
            
            
            
            int heure_deb = cbHeureDebut.getSelectedIndex()+7;
            int heure_fin = cbHeureFin.getSelectedIndex()+7;
            
            String affichageTable = "new cours";
            
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            
            Seance s = new Seance(0, df.format(this.seance_date), id_cours, id_salle, heure_deb, heure_fin, affichageTable);
            
            tools.debug(s.toString());
            
            try {
                
                da.insertSeance(s);
                
                tools.debug(mc.get(cbCours.getSelectedIndex()).getNomClasse());
                //tools.debug(mc.get(cbCours.getSelectedIndex()).getIdIe);
                
                Cours cc = mc.get(cbCours.getSelectedIndex());
                
                tools.debug(cc.toString());
                
                Salle ss = ms.get(cbSalle.getSelectedIndex());
                
                //Ue ue = new Ue(WIDTH, affichageTable, affichageTable, id_seance, heure_fin)
                
                String lareste = cc.getCoursName();
                
                int len_base = ("Salle: "+ss.getNomSalle()).length();
                int ext = len_base + lareste.length();
                
                String reste_s = "";
                
                if (ext > 139) {
                    reste_s = lareste.substring(0, 139 - len_base);
                } else {
                    reste_s = lareste;
                }
                
                tools.debug("Salle: "+ss.getNomSalle() + " "+reste_s);
                Twitter twitter = new TwitterFactory().getInstance();
                Status status = twitter.updateStatus("Salle: "+ss.getNomSalle() + " "+reste_s);
                tools.debug("Send tweet: " + status.getText());
                
            } catch (SQLException ex) {
                Logger.getLogger(FenetreAjoutModifClasse.class.getName()).log(Level.SEVERE, null, ex);
            } catch (TwitterException ex) {
                Logger.getLogger(FenetreModifSeance.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            resultat = 0;
            
            this.dispose();
            
        }
        else if (this.act == 1) {
            
        }
    }//GEN-LAST:event_btValiderActionPerformed

    private void cbGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGroupeActionPerformed

        if (cbGroupe.getSelectedIndex() != -1) {

            //recharge models
            mc.groupe = mg.get(cbGroupe.getSelectedIndex()).getIdGroupe();

            cbCours.setSelectedIndex(-1);

            try {
                //tools.debug("start");
                mc.chargerClasses();
                //tools.debug("end");
            } catch (SQLException ex) {
                Logger.getLogger(PanelGroupes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbGroupeActionPerformed

    private void cbGroupeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGroupeItemStateChanged

    }//GEN-LAST:event_cbGroupeItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btValider;
    private javax.swing.JComboBox<String> cbCours;
    private javax.swing.JComboBox<String> cbGroupe;
    private javax.swing.JComboBox<String> cbHeureDebut;
    private javax.swing.JComboBox<String> cbHeureFin;
    private javax.swing.JComboBox<String> cbSalle;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lEnseignant;
    private javax.swing.JLabel lGroupe;
    private javax.swing.JLabel lHeureDebut;
    private javax.swing.JLabel lHeureFin;
    private javax.swing.JLabel lSalle;
    private javax.swing.JLabel lTitre;
    private javax.swing.JPanel pValidationCours;
    private javax.swing.JRadioButton rbAnnule;
    private javax.swing.JRadioButton rbValide;
    // End of variables declaration//GEN-END:variables
}
