/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleUser;
import dao.DaoUser;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.table.TableModel;

/**
 *
 * @author Mateusz
 */
public class FenetreUsers extends javax.swing.JFrame {
    
    Connection cnx;
    JFrame parent;
    private ModeleUser userModel;
    private DaoUser dao;

    /**
     * Creates new form FenetreUsers
     */
    public FenetreUsers(JFrame parent, Connection cnx) {
        
        this.cnx = cnx;
        this.parent = parent;
        
        dao = new DaoUser(cnx);
        userModel = new ModeleUser(dao);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spListeUsers = new javax.swing.JScrollPane();
        tListeUsers = new javax.swing.JTable();
        btAjouterUser = new javax.swing.JButton();
        btModifierUser = new javax.swing.JButton();
        btSupprimerUser = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tListeUsers.setModel(userModel);
        spListeUsers.setViewportView(tListeUsers);

        btAjouterUser.setText("Ajouter");
        btAjouterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterUserActionPerformed(evt);
            }
        });

        btModifierUser.setText("Modifier");
        btModifierUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierUserActionPerformed(evt);
            }
        });

        btSupprimerUser.setText("Supprmier");

        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spListeUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAjouterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btModifierUser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSupprimerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRetour)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spListeUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjouterUser)
                    .addComponent(btModifierUser)
                    .addComponent(btSupprimerUser)
                    .addComponent(btRetour))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btModifierUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btModifierUserActionPerformed

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btRetourActionPerformed

    private void btAjouterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterUserActionPerformed
        //FenetreModifUser fu = new FenetreModifUser(parent, null);
        
    }//GEN-LAST:event_btAjouterUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouterUser;
    private javax.swing.JButton btModifierUser;
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btSupprimerUser;
    private javax.swing.JScrollPane spListeUsers;
    private javax.swing.JTable tListeUsers;
    // End of variables declaration//GEN-END:variables
}
