/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleClasse;
import appli.ModeleEtudiantNote;
import appli.tools;
import dao.DaoClasse;
import dao.DaoEtudiant;
import java.awt.Frame;
import java.sql.Connection;

/**
 *
 * @author paul
 */
public class FenetreSaisieNotes extends javax.swing.JFrame {
  public int action;
    
    /**
     * 0 - aucun action
     * 1 - action ok (il faut mettre à jour le vue principale)
     */
    private int resultat;
    
    public Frame parenta;
    
    public ModeleEtudiantNote modelNoteEtu;
    
    Connection cnx;

    /**
     * Creates new form FenetreGestionNotes
     */
    public FenetreSaisieNotes(java.awt.Frame parent,Connection cnx) {
        
        initComponents();
        this.cnx=cnx;
         DaoClasse daoClas =new  DaoClasse(cnx);
         DaoEtudiant daoEtu = new DaoEtudiant(cnx);
            ModeleClasse modelClass =new ModeleClasse(daoClas);
            
            //recuperation des données dans modelList
            modelNoteEtu = new ModeleEtudiantNote(daoEtu);
            
            //je met le model dans la table
           
            tListeNotes.setModel(modelNoteEtu);
            cbClasse.setModel(modelClass);
    }
   public int doModal() {
        this.setVisible(true);
        return resultat;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSaisieNotes = new javax.swing.JLabel();
        lClasse = new javax.swing.JLabel();
        cbClasse = new javax.swing.JComboBox<>();
        lUE = new javax.swing.JLabel();
        cbUE = new javax.swing.JComboBox<>();
        spListeNotes = new javax.swing.JScrollPane();
        tListeNotes = new javax.swing.JTable();
        btImporterNotes = new javax.swing.JButton();
        btEnregistrerNotes = new javax.swing.JButton();
        btAnnulerNotes = new javax.swing.JButton();
        btFinNotes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lSaisieNotes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lSaisieNotes.setText("Saisie des notes");

        lClasse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lClasse.setText("Classe");

        cbClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbClasse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClasseItemStateChanged(evt);
            }
        });
        cbClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClasseActionPerformed(evt);
            }
        });

        lUE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lUE.setText("U.E");

        cbUE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tListeNotes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tListeNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "étudiant", "note"
            }
        ));
        spListeNotes.setViewportView(tListeNotes);

        btImporterNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImporterNotes.setText("importer");

        btEnregistrerNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btEnregistrerNotes.setText("enregistrer");

        btAnnulerNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAnnulerNotes.setText("annuler");

        btFinNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btFinNotes.setText("Fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btImporterNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btEnregistrerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btAnnulerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btFinNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spListeNotes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(cbUE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(lSaisieNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lSaisieNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbClasse)
                    .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(spListeNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAnnulerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btImporterNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btEnregistrerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btFinNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClasseActionPerformed
      
    }//GEN-LAST:event_cbClasseActionPerformed

    private void cbClasseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClasseItemStateChanged
      
        int id_select = cbClasse.getSelectedIndex();
        int taille=modelNoteEtu.getRowCount();
        taille=taille;
     ModeleEtudiantNote modelNoteEtuTemp = new ModeleEtudiantNote();
     
      modelNoteEtuTemp=modelNoteEtu;
         tools.debug("talle de liste etudiant classe : " + taille);
           tools.debug("talle de liste etudiant classe temp : " + modelNoteEtuTemp.getRowCount() );
        for(int i=0;i<=taille;i++){
        if(id_select!=modelNoteEtu.getIdAt(i));
        modelNoteEtuTemp.supprimerLigne(i);
          tools.debug("talle de liste etudiant classe : " + taille);
        }
        tListeNotes.setModel(modelNoteEtuTemp); 
        
    }//GEN-LAST:event_cbClasseItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnulerNotes;
    private javax.swing.JButton btEnregistrerNotes;
    private javax.swing.JButton btFinNotes;
    private javax.swing.JButton btImporterNotes;
    private javax.swing.JComboBox<String> cbClasse;
    private javax.swing.JComboBox<String> cbUE;
    private javax.swing.JLabel lClasse;
    private javax.swing.JLabel lSaisieNotes;
    private javax.swing.JLabel lUE;
    private javax.swing.JScrollPane spListeNotes;
    private javax.swing.JTable tListeNotes;
    // End of variables declaration//GEN-END:variables
}
