/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleClasse;
import appli.ModeleEtudiantClasse;
import appli.ModeleEtudiantExamen;
import appli.ModeleEtudiantNote;
import appli.ModeleUe;
import appli.MyCellRenderer;
import appli.tools;
import dao.DaoClasse;
import dao.DaoEtudiant;
import dao.DaoUe;
import java.awt.Frame;
import java.sql.Connection;
import javax.swing.ComboBoxModel;

/**
 *
 * @author paul
 */
public class FenetreSaisieNotes extends javax.swing.JFrame {
  public int action;
    
    /**
     * 0 - aucun action
     * 1 - action ok (il faut mettre à jour le vue principale)
     */
    private int resultat;
    private int idClasse;
    public Frame parenta;
    private ModeleClasse modelClass;
    
    public ModeleEtudiantClasse modelEtuClasseNote;
    
    Connection cnx;

    /**
     * Creates new form FenetreGestionNotes
     */
    public FenetreSaisieNotes(java.awt.Frame parent,Connection cnx) {
        
        initComponents();
        idClasse=1;
        this.cnx=cnx;
         DaoClasse daoClas =new  DaoClasse(cnx);
         DaoEtudiant daoEtu = new DaoEtudiant(cnx);
         DaoUe daoUe =new DaoUe(cnx);
         modelClass =new ModeleClasse(daoClas);
         ModeleEtudiantExamen modelEtu= new ModeleEtudiantExamen(daoEtu);
            
            //recuperation des données dans modelList
            
            ModeleUe modelUe =new ModeleUe(daoUe);
            
            //je met le model dans la table
           
            tListeNotes.setModel(modelEtu);
            cbClasse.setModel(modelClass);
            cbClasse.setSelectedItem(modelClass.getElementAt(2));//a changer car lindice  change 
            cbUe.setModel( modelUe);
            cbUe.setSelectedItem(modelUe.getElementAt(1));
    }
   public int doModal() {
        this.setVisible(true);
        return resultat;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSaisieNotes = new javax.swing.JLabel();
        lClasse = new javax.swing.JLabel();
        cbClasse = new javax.swing.JComboBox<>();
        lUE = new javax.swing.JLabel();
        cbUe = new javax.swing.JComboBox<>();
        spListeNotes = new javax.swing.JScrollPane();
        tListeNotes = new javax.swing.JTable();
        btImporterNotes = new javax.swing.JButton();
        btEnregistrerNotes = new javax.swing.JButton();
        btAnnulerNotes = new javax.swing.JButton();
        btFinNotes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lSaisieNotes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lSaisieNotes.setText("Saisie des notes");

        lClasse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lClasse.setText("Classe");

        cbClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbClasse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClasseItemStateChanged(evt);
            }
        });
        cbClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClasseActionPerformed(evt);
            }
        });

        lUE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lUE.setText("U.E");

        cbUe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tListeNotes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tListeNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "étudiant", "note"
            }
        ));
        spListeNotes.setViewportView(tListeNotes);

        btImporterNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImporterNotes.setText("importer");

        btEnregistrerNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btEnregistrerNotes.setText("enregistrer");

        btAnnulerNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAnnulerNotes.setText("annuler");

        btFinNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btFinNotes.setText("Fin");
        btFinNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinNotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btImporterNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(btEnregistrerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(btAnnulerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                                .addComponent(btFinNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spListeNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(lSaisieNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(cbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbUe, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lSaisieNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbClasse, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(spListeNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btImporterNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEnregistrerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFinNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAnnulerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFinNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinNotesActionPerformed
         this.dispose();
    }//GEN-LAST:event_btFinNotesActionPerformed

    private void cbClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClasseActionPerformed

    }//GEN-LAST:event_cbClasseActionPerformed

    private void cbClasseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClasseItemStateChanged

        int id_select = modelClass.get(cbClasse.getSelectedIndex()).getIdClasse();
        tools.debug("numeros id select"+id_select);
        DaoEtudiant daoEtu = new DaoEtudiant(cnx);
        modelEtuClasseNote = new ModeleEtudiantClasse(daoEtu,id_select);

        tListeNotes.setModel(modelEtuClasseNote);
        
   
    }//GEN-LAST:event_cbClasseItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnulerNotes;
    private javax.swing.JButton btEnregistrerNotes;
    private javax.swing.JButton btFinNotes;
    private javax.swing.JButton btImporterNotes;
    private javax.swing.JComboBox<String> cbClasse;
    private javax.swing.JComboBox<String> cbUe;
    private javax.swing.JLabel lClasse;
    private javax.swing.JLabel lSaisieNotes;
    private javax.swing.JLabel lUE;
    private javax.swing.JScrollPane spListeNotes;
    private javax.swing.JTable tListeNotes;
    // End of variables declaration//GEN-END:variables
}
