/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModelModifEnseignant;
import appli.ModeleAgenda;
import appli.ModeleClasse;
import appli.ModeleEmployeur;
import appli.ModeleUser;
import appli.ModeleEtudiant;
import appli.ModeleEtudiantClasse;
import appli.ModeleEtudiantExamen;
import appli.ModeleNomEmployeur;
import appli.ModeleReferentiel;
import appli.ModeleUe;
import appli.tools;
import dao.DaoAgenda;
import dao.DaoClasse;
import dao.DaoEmployeur;
import dao.DaoEnseignant;
import dao.DaoPromotion;
import dao.DaoReferentiel;
import dao.DaoUser;
import dao.DaoEtudiant;
import dao.DaoUe;
import java.awt.Dimension;
import java.awt.Toolkit;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import metier.Enseignant;
import metier.Promotion;
import metier.User;
import metier.Etudiant;
import metier.Agenda;
import metier.CelluleAgenda;
import metier.Employeur;

/**
 *
 * @author paul
 */
public class FenetreAcceuilPrincipal extends javax.swing.JFrame {

    Connection cnx;

    JFrame parent;
    public User currentUser;
    public Promotion promotion;

    private ModeleUser userModel;
    private ModelModifEnseignant modeleEns;

    private DaoUser daoUser;
    private DaoEnseignant daoEns;
    private DaoAgenda daoAg;

    private ModeleEtudiantClasse modelEtuClasse;
    private ModeleEtudiant etuModel;
    private ModeleEtudiantExamen etuModelExam;
    private ModeleEmployeur modelNomEmp;
    private ModeleAgenda agendaModel;
    private ModeleClasse modelClass;
    private Calendar dateAgenda;

    /**
     * Creates new form Fenetre
     *
     * @param cnx
     * @param u
     */
    public FenetreAcceuilPrincipal(Connection cnx, User u) throws SQLException {

        //init connection
        this.cnx = cnx;

        //init user
        this.currentUser = u;

        initComponents();

        //init agenda date
        dateAgenda = Calendar.getInstance(Locale.FRANCE);

        //this.pGroupPane.add(new testOngletAjout());
        //preparation affichage de la fenetre principale
        //affichage de la fenetre principale
        //je cherche la promotion qui est en cours
        DaoPromotion dp = new DaoPromotion(this.cnx);
        promotion = dp.getCurrentPromotion();
        this.lAnnee.setText("Promotion en cours: " + promotion.getNomPromotion());

        //activation des fenetres
        this.lLogin.setText("User login: " + u.getLogin());
        this.lNiveau.setText("Niveau: " + u.getGroupeLibelle());

        int[] activityTable = u.getOngletsGroupes();

        for (int i = 0; i <= 5; i++) {
            if (activityTable[i] == 1) {
                pGroupPane.setEnabledAt(i, true);
            } else {
                pGroupPane.setEnabledAt(i, false);
            }
        }

        this.pGroupPane.add(new PanelClasse(cnx, this));

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();

        tools.debug("dim:" + width + " " + height);

        this.setSize(Integer.valueOf((int) width), (int) (height - 25));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pGroupPane = new javax.swing.JTabbedPane();
        pAccueil = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        lNiveau = new javax.swing.JLabel();
        lAnnee = new javax.swing.JLabel();
        pAgenda = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liAgenda = new javax.swing.JTable();
        btSemainePrec = new javax.swing.JButton();
        btSemaineNext = new javax.swing.JButton();
        btAjoutSeance = new javax.swing.JButton();
        btModifSeance = new javax.swing.JButton();
        btSuppSeance = new javax.swing.JButton();
        lSemaine = new javax.swing.JLabel();
        choixDate = new org.jdesktop.swingx.JXDatePicker();
        pGestionEtudiants = new javax.swing.JPanel();
        spEtudiants = new javax.swing.JScrollPane();
        liEtudiants = new javax.swing.JTable();
        btAjouterEtudiant = new javax.swing.JButton();
        btModifierEtudiant = new javax.swing.JButton();
        btSupprimerEtudiant = new javax.swing.JButton();
        btRestaurerEtudiant = new javax.swing.JButton();
        btAbsenceEtudiant = new javax.swing.JButton();
        btNotesEtudiant = new javax.swing.JButton();
        btPassageEtudiant = new javax.swing.JButton();
        btImporterEtudiants = new javax.swing.JButton();
        pGestionEnseignant = new javax.swing.JPanel();
        lTitreGestionEnseignants = new javax.swing.JLabel();
        jBModifEnsegnant = new javax.swing.JButton();
        jBImporter1 = new javax.swing.JButton();
        jBGestionNote1 = new javax.swing.JButton();
        btCreationEtatHeure = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        liEnseignant = new javax.swing.JTable();
        btAjouterEnseignant = new javax.swing.JButton();
        btSupprimerEnseignant = new javax.swing.JButton();
        btVoirEnseignant = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pGestionExamen = new javax.swing.JPanel();
        pSurveillantEpreuve = new javax.swing.JPanel();
        spSurveillantEpreuve = new javax.swing.JScrollPane();
        liSurveillantEpreuve = new javax.swing.JList<>();
        lNomSurveillant = new javax.swing.JLabel();
        cbSurveillanEpreuve = new javax.swing.JComboBox<>();
        btAjouter = new javax.swing.JButton();
        lUE = new javax.swing.JLabel();
        btImprimListEmargement = new javax.swing.JButton();
        cbChoixUe = new javax.swing.JComboBox<>();
        btImprimPvSurveillant = new javax.swing.JButton();
        btImprimPvIntero = new javax.swing.JButton();
        btImprimConvocEtud = new javax.swing.JButton();
        pEtudrepasUe = new javax.swing.JPanel();
        lPromo = new javax.swing.JLabel();
        cbChoixEtud = new javax.swing.JComboBox<>();
        lNomEtud = new javax.swing.JLabel();
        cbChoixEtudRepasUe = new javax.swing.JComboBox<>();
        btAjouterEtud = new javax.swing.JButton();
        btimprilConvocSurveil = new javax.swing.JButton();
        pInterogateurEpreuve = new javax.swing.JPanel();
        spListeInterogateur = new javax.swing.JScrollPane();
        liListeInterogateur = new javax.swing.JList<>();
        lNomInterogateur = new javax.swing.JLabel();
        cbChoixInterogateur = new javax.swing.JComboBox<>();
        btAjouterInterrogateur = new javax.swing.JButton();
        btImprimConvocIntrogateur = new javax.swing.JButton();
        tTitreGestionExam = new javax.swing.JLabel();
        lPromotion = new javax.swing.JLabel();
        spListeEtudConvoque = new javax.swing.JScrollPane();
        liEtudConvoquer = new javax.swing.JTable();
        cbChoixClasse = new javax.swing.JComboBox<>();
        pGestionUsers = new javax.swing.JPanel();
        spUser = new javax.swing.JScrollPane();
        LiUser = new javax.swing.JTable();
        btAjouterUser = new javax.swing.JButton();
        btSupprimer = new javax.swing.JButton();
        btModifier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemple d'utilisation des onglets");

        pGroupPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 2, 12))); // NOI18N
        pGroupPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pGroupPaneStateChanged(evt);
            }
        });

        lLogin.setText("Login:");

        lNiveau.setText("Niveau:");

        lAnnee.setText("Année en cours: ");

        javax.swing.GroupLayout pAccueilLayout = new javax.swing.GroupLayout(pAccueil);
        pAccueil.setLayout(pAccueilLayout);
        pAccueilLayout.setHorizontalGroup(
            pAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLogin)
                    .addComponent(lNiveau)
                    .addComponent(lAnnee))
                .addContainerGap(1403, Short.MAX_VALUE))
        );
        pAccueilLayout.setVerticalGroup(
            pAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNiveau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnnee)
                .addContainerGap(834, Short.MAX_VALUE))
        );

        pGroupPane.addTab("Accueil", pAccueil);

        liAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        liAgenda.setCellSelectionEnabled(true);
        liAgenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(liAgenda);

        btSemainePrec.setText("Semaine Precedant");
        btSemainePrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSemainePrecActionPerformed(evt);
            }
        });

        btSemaineNext.setText("Semaine Prochaine");
        btSemaineNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSemaineNextActionPerformed(evt);
            }
        });

        btAjoutSeance.setText("Ajout Seance");
        btAjoutSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjoutSeanceActionPerformed(evt);
            }
        });

        btModifSeance.setText("Modifier Seance");
        btModifSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifSeanceActionPerformed(evt);
            }
        });

        btSuppSeance.setText("Supprmier Seance");

        lSemaine.setText("jLabel1");

        choixDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAgendaLayout = new javax.swing.GroupLayout(pAgenda);
        pAgenda.setLayout(pAgendaLayout);
        pAgendaLayout.setHorizontalGroup(
            pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1475, Short.MAX_VALUE)
                    .addGroup(pAgendaLayout.createSequentialGroup()
                        .addGroup(pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAgendaLayout.createSequentialGroup()
                                .addGroup(pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pAgendaLayout.createSequentialGroup()
                                        .addComponent(btAjoutSeance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btModifSeance))
                                    .addComponent(choixDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAgendaLayout.createSequentialGroup()
                                        .addComponent(btSemainePrec)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btSemaineNext))
                                    .addComponent(btSuppSeance)))
                            .addComponent(lSemaine))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pAgendaLayout.setVerticalGroup(
            pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAgendaLayout.createSequentialGroup()
                .addGroup(pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAgendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSemainePrec)
                            .addComponent(btSemaineNext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAgendaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(choixDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lSemaine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjoutSeance)
                    .addComponent(btModifSeance)
                    .addComponent(btSuppSeance))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pGroupPane.addTab("Agenda", pAgenda);

        pGestionEtudiants.setEnabled(false);

        spEtudiants.setViewportView(liEtudiants);

        btAjouterEtudiant.setText("Ajouter");
        btAjouterEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterEtudiantActionPerformed(evt);
            }
        });

        btModifierEtudiant.setText("Modifier");
        btModifierEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierEtudiantActionPerformed(evt);
            }
        });

        btSupprimerEtudiant.setText("Supprimer");
        btSupprimerEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerEtudiantActionPerformed(evt);
            }
        });

        btRestaurerEtudiant.setText("Restaurer la fiche d'un étudiant");

        btAbsenceEtudiant.setText("Gestion des abscences");

        btNotesEtudiant.setText("Gestion des notes");
        btNotesEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNotesEtudiantActionPerformed(evt);
            }
        });

        btPassageEtudiant.setText("Passage des étudiants en classe supérieure");

        btImporterEtudiants.setText("Importation à partir d'un fichier");

        javax.swing.GroupLayout pGestionEtudiantsLayout = new javax.swing.GroupLayout(pGestionEtudiants);
        pGestionEtudiants.setLayout(pGestionEtudiantsLayout);
        pGestionEtudiantsLayout.setHorizontalGroup(
            pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionEtudiantsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pGestionEtudiantsLayout.createSequentialGroup()
                        .addComponent(btAjouterEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btModifierEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSupprimerEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRestaurerEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spEtudiants, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGestionEtudiantsLayout.createSequentialGroup()
                        .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPassageEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAbsenceEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btNotesEtudiant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btImporterEtudiants, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(887, Short.MAX_VALUE))
        );
        pGestionEtudiantsLayout.setVerticalGroup(
            pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionEtudiantsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spEtudiants, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAjouterEtudiant)
                        .addComponent(btSupprimerEtudiant)
                        .addComponent(btModifierEtudiant))
                    .addComponent(btRestaurerEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAbsenceEtudiant)
                    .addComponent(btNotesEtudiant))
                .addGap(18, 18, 18)
                .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btImporterEtudiants)
                    .addComponent(btPassageEtudiant))
                .addContainerGap(484, Short.MAX_VALUE))
        );

        pGroupPane.addTab("Gestion des étudiants", pGestionEtudiants);

        pGestionEnseignant.setEnabled(false);

        lTitreGestionEnseignants.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lTitreGestionEnseignants.setText("   Gestion des enseignants");

        jBModifEnsegnant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBModifEnsegnant.setText("modifier");
        jBModifEnsegnant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifEnsegnantActionPerformed(evt);
            }
        });

        jBImporter1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBImporter1.setText("Importation à partir d'un fichier");

        jBGestionNote1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBGestionNote1.setText("Gestion des cours faits");

        btCreationEtatHeure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCreationEtatHeure.setText("creation d'état des heures");

        jScrollPane1.setViewportView(liEnseignant);

        btAjouterEnseignant.setText("Ajouter");
        btAjouterEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterEnseignantActionPerformed(evt);
            }
        });

        btSupprimerEnseignant.setText("Supprimer");
        btSupprimerEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerEnseignantActionPerformed(evt);
            }
        });

        btVoirEnseignant.setText("voir");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pGestionEnseignantLayout = new javax.swing.GroupLayout(pGestionEnseignant);
        pGestionEnseignant.setLayout(pGestionEnseignantLayout);
        pGestionEnseignantLayout.setHorizontalGroup(
            pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(lTitreGestionEnseignants))
                    .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btCreationEtatHeure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBGestionNote1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jBImporter1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btAjouterEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jBModifEnsegnant, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btSupprimerEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btVoirEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(615, Short.MAX_VALUE))
        );
        pGestionEnseignantLayout.setVerticalGroup(
            pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGestionEnseignantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitreGestionEnseignants, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModifEnsegnant, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSupprimerEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAjouterEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoirEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGestionNote1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBImporter1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCreationEtatHeure, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        pGroupPane.addTab("Gestion des enseignants", pGestionEnseignant);

        pSurveillantEpreuve.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "surveillant de l'épreuve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        spSurveillantEpreuve.setViewportView(liSurveillantEpreuve);

        lNomSurveillant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomSurveillant.setText("Nom du surveillant");

        cbSurveillanEpreuve.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjouter.setText("Ajouter");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSurveillantEpreuveLayout = new javax.swing.GroupLayout(pSurveillantEpreuve);
        pSurveillantEpreuve.setLayout(pSurveillantEpreuveLayout);
        pSurveillantEpreuveLayout.setHorizontalGroup(
            pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(spSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                        .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                        .addComponent(lNomSurveillant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(cbSurveillanEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        pSurveillantEpreuveLayout.setVerticalGroup(
            pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomSurveillant, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSurveillanEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lUE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lUE.setText("U.E");

        btImprimListEmargement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimListEmargement.setText("imprimer liste d'emargement");

        btImprimPvSurveillant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimPvSurveillant.setText("imprimer Pv de surveillance");

        btImprimPvIntero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimPvIntero.setText("imprimer Pv d'interogation");

        btImprimConvocEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimConvocEtud.setText("Imprimer convocation étudiants");

        pEtudrepasUe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Etudiants devant repasser l'U.E.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lPromo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPromo.setText("promotion");

        cbChoixEtud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lNomEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomEtud.setText("nom de l'étudiant");

        cbChoixEtudRepasUe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAjouterEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjouterEtud.setText("Ajouter");

        javax.swing.GroupLayout pEtudrepasUeLayout = new javax.swing.GroupLayout(pEtudrepasUe);
        pEtudrepasUe.setLayout(pEtudrepasUeLayout);
        pEtudrepasUeLayout.setHorizontalGroup(
            pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEtudrepasUeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbChoixEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lNomEtud)
                .addGap(88, 88, 88)
                .addComponent(cbChoixEtudRepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(pEtudrepasUeLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(btAjouterEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pEtudrepasUeLayout.setVerticalGroup(
            pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEtudrepasUeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChoixEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNomEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChoixEtudRepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btAjouterEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        btimprilConvocSurveil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btimprilConvocSurveil.setText("Imprimer convocation surveillant");

        pInterogateurEpreuve.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "interrogateur pour l'épreuve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        liListeInterogateur.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spListeInterogateur.setViewportView(liListeInterogateur);

        lNomInterogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomInterogateur.setText("Nom de l'interogateur");

        cbChoixInterogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbChoixInterogateur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAjouterInterrogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjouterInterrogateur.setText("Ajoute");

        javax.swing.GroupLayout pInterogateurEpreuveLayout = new javax.swing.GroupLayout(pInterogateurEpreuve);
        pInterogateurEpreuve.setLayout(pInterogateurEpreuveLayout);
        pInterogateurEpreuveLayout.setHorizontalGroup(
            pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btAjouterInterrogateur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInterogateurEpreuveLayout.createSequentialGroup()
                .addGroup(pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pInterogateurEpreuveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spListeInterogateur))
                    .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNomInterogateur)
                        .addGap(64, 64, 64)
                        .addComponent(cbChoixInterogateur, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        pInterogateurEpreuveLayout.setVerticalGroup(
            pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomInterogateur)
                    .addComponent(cbChoixInterogateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btAjouterInterrogateur)
                .addGap(30, 30, 30)
                .addComponent(spListeInterogateur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btImprimConvocIntrogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimConvocIntrogateur.setText("Imprimer convocation interrogateur");

        tTitreGestionExam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tTitreGestionExam.setText("gestion des examens");

        lPromotion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPromotion.setText("promotion");

        liEtudConvoquer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nom", "prénom", "convoqué", "non convoqué"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spListeEtudConvoque.setViewportView(liEtudConvoquer);

        cbChoixClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbChoixClasse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbChoixClasseItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pGestionExamenLayout = new javax.swing.GroupLayout(pGestionExamen);
        pGestionExamen.setLayout(pGestionExamenLayout);
        pGestionExamenLayout.setHorizontalGroup(
            pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionExamenLayout.createSequentialGroup()
                .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGestionExamenLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(spListeEtudConvoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGestionExamenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(cbChoixClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(872, Short.MAX_VALUE))
            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionExamenLayout.createSequentialGroup()
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(389, 389, 389)
                            .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(cbChoixUe, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(305, 305, 305)
                            .addComponent(tTitreGestionExam, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pEtudrepasUe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pGestionExamenLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(pSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(pInterogateurEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(18, 18, 18)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btImprimConvocEtud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimListEmargement, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btImprimConvocIntrogateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimPvSurveillant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btimprilConvocSurveil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimPvIntero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        pGestionExamenLayout.setVerticalGroup(
            pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionExamenLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChoixClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(spListeEtudConvoque, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(605, Short.MAX_VALUE))
            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionExamenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tTitreGestionExam, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbChoixUe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(btImprimListEmargement, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(31, 31, 31)
                    .addComponent(btImprimConvocEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(pEtudrepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pInterogateurEpreuve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pSurveillantEpreuve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGestionExamenLayout.createSequentialGroup()
                            .addComponent(btimprilConvocSurveil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btImprimPvSurveillant, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btImprimConvocIntrogateur, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btImprimPvIntero, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pGroupPane.addTab("Gestion des examens", pGestionExamen);

        pGestionUsers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                showUsers(evt);
            }
        });
        pGestionUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pGestionUsersMouseClicked(evt);
            }
        });

        spUser.setViewportView(LiUser);

        btAjouterUser.setText("Ajouter");
        btAjouterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterUserActionPerformed(evt);
            }
        });

        btSupprimer.setText("Supprimer");
        btSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerActionPerformed(evt);
            }
        });

        btModifier.setText("Modifier");
        btModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pGestionUsersLayout = new javax.swing.GroupLayout(pGestionUsers);
        pGestionUsers.setLayout(pGestionUsersLayout);
        pGestionUsersLayout.setHorizontalGroup(
            pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spUser, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pGestionUsersLayout.createSequentialGroup()
                        .addComponent(btAjouterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSupprimer)))
                .addContainerGap(887, Short.MAX_VALUE))
        );
        pGestionUsersLayout.setVerticalGroup(
            pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spUser, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjouterUser)
                    .addComponent(btSupprimer)
                    .addComponent(btModifier))
                .addContainerGap(566, Short.MAX_VALUE))
        );

        pGroupPane.addTab("Gestion des users", pGestionUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pGroupPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pGroupPane, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBModifEnsegnantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifEnsegnantActionPerformed
        DaoEmployeur daoEmp = new DaoEmployeur(cnx);

        ModeleNomEmployeur modelNomEmp = new ModeleNomEmployeur(daoEmp);

        FenetreModifEnseignant fmu;

        int selected_row = liEnseignant.getSelectedRow();

        try {

            //TODO: ajouter verif selection 
            fmu = new FenetreModifEnseignant(this, modeleEns.get(selected_row), modelNomEmp, "Modifier fiche enseignant", cnx);

            int ret = fmu.doModal();

            tools.debug("modifier retour: " + ret);
            /**
             * mettre a jour la liste if (ret == 1) {
             * modeleEns.supprimerLigne(selected_row); }
        *
             */
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "selectionner un enseignant dans la liste ",
                    "information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBModifEnsegnantActionPerformed

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAjouterActionPerformed

    private void showUsers(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_showUsers
    }//GEN-LAST:event_showUsers

    private void pGestionUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGestionUsersMouseClicked
    }//GEN-LAST:event_pGestionUsersMouseClicked

    private void pGroupPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pGroupPaneStateChanged

        //TODO: juste pour le periode de dev, apres il faut mettre toutes les
        // pane's dans ce propres classes
        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();

        //onglet users
        if (index == 5) {
            tools.debug("->GestionUsers");

            //init de dao pour recuperation des données
            //1 seule dao par fonctionalité
            daoUser = new DaoUser(cnx);

            //recuperation des données dans modelList
            userModel = new ModeleUser(daoUser);

            //je met le model dans la table
            LiUser.setModel(userModel);

        } else if (index == 3) {
            //onglet enseignant

            //TODO: Paul mettre model + dao d'ensegeignant
            tools.debug("->GestionEnseignants");

            daoEns = new DaoEnseignant(cnx);

            modeleEns = new ModelModifEnseignant(daoEns);

            liEnseignant.setModel(modeleEns);

        } else if (index == 2) {
            // Onglet Etudiants
            tools.debug("->GestionEtudiants");

            //init de dao pour recuperation des données
            //1 seule dao par fonctionalité
            DaoEtudiant daoEtu = new DaoEtudiant(cnx);

            //recuperation des données dans modelList
            etuModel = new ModeleEtudiant(daoEtu);

            //je met le model dans la table
            liEtudiants.setModel(etuModel);

        } else if (index == 4) {
            // Onglet gestion examen
            tools.debug("->GestionExamen");

            //init de dao pour recuperation des données
            //1 seule dao par fonctionalité
            DaoEtudiant daoEtuExam = new DaoEtudiant(cnx);
            DaoClasse daoClas = new DaoClasse(cnx);
            DaoUe daoUe = new DaoUe(cnx);
            ModeleUe modelUe = new ModeleUe(daoUe);

            modelClass = new ModeleClasse(daoClas);
            //recuperation des données dans modelList
            etuModelExam = new ModeleEtudiantExamen(daoEtuExam);
            cbChoixClasse.setModel(modelClass);
            cbChoixClasse.setSelectedItem(modelClass.getElementAt(2));//a changer car lindice  change 
            liEtudConvoquer.setModel(etuModelExam);
            cbChoixUe.setModel(modelUe);
            cbChoixUe.setSelectedItem(modelUe.getElementAt(1));

        } else if (index == 1) {
            //TODO here
            //Agenda affichage

            tools.debug("->Agenda");

            lSemaine.setText("Semaine " + Agenda.getWeek(dateAgenda));

            choixDate.setDate(dateAgenda.getTime());

            daoAg = new DaoAgenda(cnx);

            try {

                agendaModel = new ModeleAgenda(daoAg, Agenda.getDateDebut(dateAgenda),
                        Agenda.getDateFin(dateAgenda));

            } catch (SQLException ex) {
                Logger.getLogger(FenetreAcceuilPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            liAgenda.setModel(agendaModel);

            //init agenda visibility
            for (int i = 0; i <= agendaModel.getRowCount(); i++) {
                liAgenda.setRowHeight(i, 55);
            }

            liAgenda.getColumnModel().getColumn(0).setMaxWidth(62);

        }
    }//GEN-LAST:event_pGroupPaneStateChanged

    private void btAjouterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterUserActionPerformed

        //init de dao pour recuperation des données
        DaoReferentiel daoRef = new DaoReferentiel(cnx);

        //recuperation des données dans modelList
        ModeleReferentiel refModel = new ModeleReferentiel(daoRef, "userGroupes");

        User u = new User();

        FenetreAjoutModifUser fmu = new FenetreAjoutModifUser(this, //fenetre pere
                u, //ma selection d'user
                refModel, //mon modele de groupes
                0,
                cnx);

        if (fmu.doModal()) {
            userModel.insererLigne(u);
        }

    }//GEN-LAST:event_btAjouterUserActionPerformed

    private void btAjouterEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterEnseignantActionPerformed

        DaoEmployeur daoEmp = new DaoEmployeur(cnx);
        ModeleNomEmployeur modelNomEmp = new ModeleNomEmployeur(daoEmp);
        FenetreModifEnseignant fmu;

        Enseignant ens = new Enseignant();

        try {
            fmu = new FenetreModifEnseignant(this, ens, modelNomEmp, "Ajouter fiche Enseignant", cnx);
            int ret = fmu.doModal();

            tools.debug("Ajout retour: " + ens.getNomEnseignant());

            modeleEns.insererLigne(ens);

            if (ret == 1) {
                //modeleEns.addTableModelListener(LiUser
                //modeleEns.insererLigne(null);
                //teste commit
            }

        } catch (Exception e) {
            /*JOptionPane.showMessageDialog(null, "selectionner un enseignant dans la liste ",
"information", JOptionPane.INFORMATION_MESSAGE); */
        }
    }//GEN-LAST:event_btAjouterEnseignantActionPerformed

    private void btSupprimerEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerEnseignantActionPerformed

        DaoEmployeur daoEmp = new DaoEmployeur(cnx);

        ModeleNomEmployeur modelNomEmp = new ModeleNomEmployeur(daoEmp);

        FenetreModifEnseignant fmu;

        int selected_row = liEnseignant.getSelectedRow();

        try {

            //TODO: ajouter verif selection 
            fmu = new FenetreModifEnseignant(this, modeleEns.get(selected_row), modelNomEmp, "Suprimer fiche Enseignant", cnx);

            int ret = fmu.doModal();

            tools.debug("Suppression retour: " + ret);

            if (ret == 1) {
                modeleEns.supprimerLigne(selected_row);
            }

        } catch (Exception e) {

            // JOptionPane.showMessageDialog(null, "selectionner un enseignant dans la liste ",
            //  "information", JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_btSupprimerEnseignantActionPerformed

    private void btAjouterEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterEtudiantActionPerformed
        //DaoEtudiant daoEtu =new   DaoEtudiant(cnx);

        //ModeleEtudiant modeleEtu=new ModeleEtudiant(daoEtu);
        //int selected_row = liEtudiants.getSelectedRow();
        FenetreModifSuprEtudiant fmu;
        Etudiant etu = new Etudiant();
        try {
            //fmu = new FenetreModifEnseignant(this,modeleEns.get(selected_row),modelNomEmp,"Suprimer fiche Enseignant",cnx);
            fmu = new FenetreModifSuprEtudiant(this,
                    etu, "Ajouter fiche Etudiant", cnx);
            int ret = fmu.doModal();
            etuModel.insererLigne(etu);
            if (ret == 1) {
                //etuModel.supprimerLigne(selected_row);
            }
        } catch (Exception e) {
            // JOptionPane.showMessageDialog(null, "selectionner un Etudiant ",
//"information", JOptionPane.INFORMATION_MESSAGE); 
        }

    }//GEN-LAST:event_btAjouterEtudiantActionPerformed

    private void btModifierEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierEtudiantActionPerformed

        //DaoEtudiant daoEtu =new   DaoEtudiant(cnx);
        //ModeleEtudiant modeleEtu=new ModeleEtudiant(daoEtu);
        int selected_row = liEtudiants.getSelectedRow();
        FenetreModifSuprEtudiant fmu;
        try {
            //fmu = new FenetreModifEnseignant(this,modeleEns.get(selected_row),modelNomEmp,"Suprimer fiche Enseignant",cnx);
            fmu = new FenetreModifSuprEtudiant(this,
                    etuModel.getEtu(selected_row), "Modifier fiche Etudiant", cnx);
            int ret = fmu.doModal();
            /**
             * if (ret == 1) { etuModel.supprimerLigne(selected_row); }
         *
             */
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "selectionner un Etudiant ",
                    "information", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btModifierEtudiantActionPerformed

    private void btSupprimerEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerEtudiantActionPerformed

        //DaoEtudiant daoEtu =new   DaoEtudiant(cnx);
        //ModeleEtudiant modeleEtu=new ModeleEtudiant(daoEtu);
        int selected_row = liEtudiants.getSelectedRow();
        FenetreModifSuprEtudiant fmu;
        try {
            //fmu = new FenetreModifEnseignant(this,modeleEns.get(selected_row),modelNomEmp,"Suprimer fiche Enseignant",cnx);
            fmu = new FenetreModifSuprEtudiant(this,
                    etuModel.getEtu(selected_row), "Suprimer fiche Etudiant", cnx);
            int ret = fmu.doModal();
            if (ret == 1) {
                etuModel.supprimerLigne(selected_row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "selectionner un Etudiant ",
                    "information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSupprimerEtudiantActionPerformed

    private void btSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerActionPerformed
        try {

            if (LiUser.getSelectedRow() != -1) {

                int result;
                String login_suppresion = this.userModel.getLogin(LiUser.getSelectedRow());

                CallableStatement cstmt = cnx.prepareCall("{ ? = call supprimer_user(?)}");

                cstmt.registerOutParameter(1, Types.INTEGER);
                cstmt.setString(2, login_suppresion);
                cstmt.execute();
                result = cstmt.getInt(1);
                tools.debug("Suppresion : " + result);

                if (result == 1) {
                    this.userModel.supprimerLigne(LiUser.getSelectedRow());

                    JOptionPane.showMessageDialog(null, "Utilisateur " + login_suppresion + " a été bien supprimé",
                            "Information", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    //result != 1
                    throw new Exception("Impossible de supprimer utilisateur");
                }

            } else {
                throw new Exception("Selectionner un User");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSupprimerActionPerformed

    private void btModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierActionPerformed

        //init de dao pour recuperation des données
        DaoReferentiel daoRef = new DaoReferentiel(cnx);

        //recuperation des données dans modelList
        ModeleReferentiel refModel = new ModeleReferentiel(daoRef, "userGroupes");

        FenetreAjoutModifUser fmu = new FenetreAjoutModifUser(this, //fenetre pere
                this.userModel.get(LiUser.getSelectedRow()), //ma selection d'user
                refModel, //mon modele de groupes
                1,
                cnx);

        fmu.doModal();

    }//GEN-LAST:event_btModifierActionPerformed

    private void btSemainePrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSemainePrecActionPerformed

        Agenda.setPreviousWeek(dateAgenda);
        //lDate.setText("Aujourd'hui " + Agenda.getDate(dateAgenda));
        lSemaine.setText("Semaine " + Agenda.getWeek(dateAgenda));
        choixDate.setDate(dateAgenda.getTime());

        //TODO: put getter et setter
        agendaModel.date_debut = Agenda.getDateDebut(dateAgenda);
        agendaModel.date_fin = Agenda.getDateFin(dateAgenda);

        tools.debug("new date: " + agendaModel.date_debut + "->" + agendaModel.date_fin);

        try {
            agendaModel.charger();
        } catch (SQLException ex) {
            Logger.getLogger(FenetreAcceuilPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //init agenda visibility
        for (int i = 0; i <= agendaModel.getRowCount(); i++) {
            liAgenda.setRowHeight(i, 55);
        }

        liAgenda.getColumnModel().getColumn(0).setMaxWidth(62);

    }//GEN-LAST:event_btSemainePrecActionPerformed

    private void btSemaineNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSemaineNextActionPerformed

        Agenda.setNextWeek(dateAgenda);
        //lDate.setText("Aujourd'hui " + Agenda.getDate(dateAgenda));
        lSemaine.setText("Semaine " + Agenda.getWeek(dateAgenda));
        choixDate.setDate(dateAgenda.getTime());

        //TODO: put getter et setter
        agendaModel.date_debut = Agenda.getDateDebut(dateAgenda);
        agendaModel.date_fin = Agenda.getDateFin(dateAgenda);

        tools.debug("new date: " + agendaModel.date_debut + "->" + agendaModel.date_fin);

        try {
            agendaModel.charger();
        } catch (SQLException ex) {
            Logger.getLogger(FenetreAcceuilPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //init agenda visibility
        for (int i = 0; i <= agendaModel.getRowCount(); i++) {
            liAgenda.setRowHeight(i, 55);
        }

        liAgenda.getColumnModel().getColumn(0).setMaxWidth(62);

    }//GEN-LAST:event_btSemaineNextActionPerformed

    private void choixDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixDateActionPerformed

        //tools.debug("test");
        dateAgenda.setTime(choixDate.getDate());
        lSemaine.setText("Semaine " + Agenda.getWeek(dateAgenda));

        //TODO: put getter et setter
        agendaModel.date_debut = Agenda.getDateDebut(dateAgenda);
        agendaModel.date_fin = Agenda.getDateFin(dateAgenda);

        tools.debug("new date: " + agendaModel.date_debut + "->" + agendaModel.date_fin);

        try {
            agendaModel.charger();
        } catch (SQLException ex) {
            Logger.getLogger(FenetreAcceuilPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //init agenda visibility
        for (int i = 0; i <= agendaModel.getRowCount(); i++) {
            liAgenda.setRowHeight(i, 55);
        }

        liAgenda.getColumnModel().getColumn(0).setMaxWidth(62);

    }//GEN-LAST:event_choixDateActionPerformed

    private void btModifSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifSeanceActionPerformed

        CelluleAgenda ca = agendaModel.getObjetAt(liAgenda.getSelectedRow(), liAgenda.getSelectedColumn());

        FenetreModifSeance fs = null;

        try {
            fs = new FenetreModifSeance(this, ca, cnx, 1);
        } catch (ParseException ex) {
            Logger.getLogger(FenetreAcceuilPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FenetreAcceuilPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //if - actions
        fs.doModal();

    }//GEN-LAST:event_btModifSeanceActionPerformed

    private void btAjoutSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjoutSeanceActionPerformed

        CelluleAgenda ca = agendaModel.getObjetAt(liAgenda.getSelectedRow(), liAgenda.getSelectedColumn());

        FenetreModifSeance fs = null;

        try {
            fs = new FenetreModifSeance(this, ca, cnx, 0);
        } catch (ParseException ex) {
            Logger.getLogger(FenetreAcceuilPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FenetreAcceuilPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //if - actions
        fs.doModal();
    }//GEN-LAST:event_btAjoutSeanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DaoEmployeur daoEmp = null;
        ModeleNomEmployeur modelNomEmp = new ModeleNomEmployeur(daoEmp);

        Employeur emp = new Employeur();

        try {

            FenetreAjoutEmployeur fmu;
            fmu = new FenetreAjoutEmployeur(this,
                    emp, cnx);
            int ret = fmu.doModal();
            //etuModel.insererLigne(etu);
            if (ret == 1) {
                //etuModel.supprimerLigne(selected_row);
            }
        } catch (Exception e) {
            // JOptionPane.showMessageDialog(null, "selectionner un Etudiant ",
//"information", JOptionPane.INFORMATION_MESSAGE); 
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btNotesEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNotesEtudiantActionPerformed

        try {

            FenetreSaisieNotes fmu;
            fmu = new FenetreSaisieNotes(this, cnx);

            int ret = fmu.doModal();
            //etuModel.insererLigne(etu);
            if (ret == 1) {
                //etuModel.supprimerLigne(selected_row);
            }
        } catch (Exception e) {
            // JOptionPane.showMessageDialog(null, "selectionner un Etudiant ",
//"information", JOptionPane.INFORMATION_MESSAGE); 
        }

    }//GEN-LAST:event_btNotesEtudiantActionPerformed

    private void cbChoixClasseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChoixClasseItemStateChanged
        int id_select = modelClass.get(cbChoixClasse.getSelectedIndex()).getIdClasse();
        tools.debug("numeros id select" + id_select);
        DaoEtudiant daoEtu = new DaoEtudiant(cnx);
        modelEtuClasse = new ModeleEtudiantClasse(daoEtu, id_select);
        liEtudConvoquer.setModel(modelEtuClasse);
    }//GEN-LAST:event_cbChoixClasseItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LiUser;
    private javax.swing.JButton btAbsenceEtudiant;
    private javax.swing.JButton btAjoutSeance;
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btAjouterEnseignant;
    private javax.swing.JButton btAjouterEtud;
    private javax.swing.JButton btAjouterEtudiant;
    private javax.swing.JButton btAjouterInterrogateur;
    private javax.swing.JButton btAjouterUser;
    private javax.swing.JButton btCreationEtatHeure;
    private javax.swing.JButton btImporterEtudiants;
    private javax.swing.JButton btImprimConvocEtud;
    private javax.swing.JButton btImprimConvocIntrogateur;
    private javax.swing.JButton btImprimListEmargement;
    private javax.swing.JButton btImprimPvIntero;
    private javax.swing.JButton btImprimPvSurveillant;
    private javax.swing.JButton btModifSeance;
    private javax.swing.JButton btModifier;
    private javax.swing.JButton btModifierEtudiant;
    private javax.swing.JButton btNotesEtudiant;
    private javax.swing.JButton btPassageEtudiant;
    private javax.swing.JButton btRestaurerEtudiant;
    private javax.swing.JButton btSemaineNext;
    private javax.swing.JButton btSemainePrec;
    private javax.swing.JButton btSuppSeance;
    private javax.swing.JButton btSupprimer;
    private javax.swing.JButton btSupprimerEnseignant;
    private javax.swing.JButton btSupprimerEtudiant;
    private javax.swing.JButton btVoirEnseignant;
    private javax.swing.JButton btimprilConvocSurveil;
    private javax.swing.JComboBox<String> cbChoixClasse;
    private javax.swing.JComboBox<String> cbChoixEtud;
    private javax.swing.JComboBox<String> cbChoixEtudRepasUe;
    private javax.swing.JComboBox<String> cbChoixInterogateur;
    private javax.swing.JComboBox<String> cbChoixUe;
    private javax.swing.JComboBox<String> cbSurveillanEpreuve;
    private org.jdesktop.swingx.JXDatePicker choixDate;
    private javax.swing.JButton jBGestionNote1;
    private javax.swing.JButton jBImporter1;
    private javax.swing.JButton jBModifEnsegnant;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lAnnee;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lNiveau;
    private javax.swing.JLabel lNomEtud;
    private javax.swing.JLabel lNomInterogateur;
    private javax.swing.JLabel lNomSurveillant;
    private javax.swing.JLabel lPromo;
    private javax.swing.JLabel lPromotion;
    private javax.swing.JLabel lSemaine;
    private javax.swing.JLabel lTitreGestionEnseignants;
    private javax.swing.JLabel lUE;
    private javax.swing.JTable liAgenda;
    private javax.swing.JTable liEnseignant;
    private javax.swing.JTable liEtudConvoquer;
    private javax.swing.JTable liEtudiants;
    private javax.swing.JList<String> liListeInterogateur;
    private javax.swing.JList<String> liSurveillantEpreuve;
    private javax.swing.JPanel pAccueil;
    private javax.swing.JPanel pAgenda;
    private javax.swing.JPanel pEtudrepasUe;
    private javax.swing.JPanel pGestionEnseignant;
    private javax.swing.JPanel pGestionEtudiants;
    private javax.swing.JPanel pGestionExamen;
    private javax.swing.JPanel pGestionUsers;
    private javax.swing.JTabbedPane pGroupPane;
    private javax.swing.JPanel pInterogateurEpreuve;
    private javax.swing.JPanel pSurveillantEpreuve;
    private javax.swing.JScrollPane spEtudiants;
    private javax.swing.JScrollPane spListeEtudConvoque;
    private javax.swing.JScrollPane spListeInterogateur;
    private javax.swing.JScrollPane spSurveillantEpreuve;
    private javax.swing.JScrollPane spUser;
    private javax.swing.JLabel tTitreGestionExam;
    // End of variables declaration//GEN-END:variables
}
