/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModelePromotion;
import appli.tools;
import dao.DaoClasse;
import dao.DaoGroupe;
import dao.DaoPromotion;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import metier.Classe;
import metier.Groupe;
import metier.Promotion;

/**
 *
 * @author Mateusz
 */
public class FenetreAjoutModifGroupe extends javax.swing.JDialog {
    
    public int resultat;
    
    ModelePromotion mp;
    
    DaoPromotion dao;
    DaoGroupe daoC;
    
    public Groupe maclass;

    /**
     * Creates new form FenetreAjoutModifClasse
     * @param parent
     * @param c
     * @param cnx
     */
    public FenetreAjoutModifGroupe(java.awt.Frame parent, Groupe c, Connection cnx) {
        
        super(parent, true);
        initComponents();
        
        this.setTitle("Ajout du groupe");
        
        resultat = 1;
        
        dao = new DaoPromotion(cnx);
        daoC = new DaoGroupe(cnx);
        
        mp = new ModelePromotion(dao);
        
        this.maclass = c;
        
        this.lClasse.setText(c.getNomClasse());
        
    }
    
    public Groupe doModal() {
        this.setVisible(true);
        return maclass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCode = new javax.swing.JLabel();
        txCode = new javax.swing.JTextField();
        lPromotion = new javax.swing.JLabel();
        bAjout = new javax.swing.JButton();
        bAnnuler = new javax.swing.JButton();
        lClasse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lCode.setText("Code");

        lPromotion.setText("Classe");

        bAjout.setText("Ajouter");
        bAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjoutActionPerformed(evt);
            }
        });

        bAnnuler.setText("Annuler");
        bAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnulerActionPerformed(evt);
            }
        });

        lClasse.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCode)
                    .addComponent(lPromotion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lClasse)
                    .addComponent(txCode, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bAjout)
                .addGap(30, 30, 30)
                .addComponent(bAnnuler)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPromotion)
                    .addComponent(lClasse))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCode)
                    .addComponent(txCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAjout)
                    .addComponent(bAnnuler))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjoutActionPerformed
        
        //preparation ajout
        String code = txCode.getText();
        
        if ("".equals(code)) {
            
        } else {
            
            maclass.setNom(code);
            
            tools.debug(maclass.toString());
            
            try {
                daoC.insertGroupe(maclass);
                
            } catch (SQLException ex) {
                Logger.getLogger(FenetreAjoutModifGroupe.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            resultat = 0;
            
            this.dispose();
        }
        
    }//GEN-LAST:event_bAjoutActionPerformed

    private void bAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_bAnnulerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAjout;
    private javax.swing.JButton bAnnuler;
    private javax.swing.JLabel lClasse;
    private javax.swing.JLabel lCode;
    private javax.swing.JLabel lPromotion;
    private javax.swing.JTextField txCode;
    // End of variables declaration//GEN-END:variables
}
