/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleUser;
import dao.daoUser;
import java.awt.Component;
import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author Alain
 */
public class FenetreAcceuilPrincipal extends javax.swing.JFrame {
     
 Connection cnx;
    
    JFrame parent;
    private ModeleUser userModel;
    private daoUser dao;
    /**
     * Creates new form Fenetre
     */
    public FenetreAcceuilPrincipal(Connection cnx) {
         this.cnx = cnx;
        initComponents();
        pGestionEtudiant.setEnabledAt(1, false);
        pGestionEtudiant.setEnabledAt(2, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pGestionEtudiant = new javax.swing.JTabbedPane();
        pAgenda = new javax.swing.JPanel();
        pGestionEtudiants = new javax.swing.JPanel();
        jBGestionAbscence = new javax.swing.JButton();
        jBGestionNote = new javax.swing.JButton();
        btRestFichEtu = new javax.swing.JButton();
        btPassageEtuClasSup = new javax.swing.JButton();
        lTitreGestEtu = new javax.swing.JLabel();
        jBCreaSuprEtudiabnt = new javax.swing.JButton();
        jBModifEtudiant = new javax.swing.JButton();
        jBImporter = new javax.swing.JButton();
        pGestionEnseignant = new javax.swing.JPanel();
        lTitreGestionEnseignants = new javax.swing.JLabel();
        btCreaSuprEtudiabnt1 = new javax.swing.JButton();
        jBModifEtudiant1 = new javax.swing.JButton();
        jBImporter1 = new javax.swing.JButton();
        jBGestionNote1 = new javax.swing.JButton();
        btCreationEtatHeure = new javax.swing.JButton();
        pGestionExamen = new javax.swing.JPanel();
        pSurveillantEpreuve = new javax.swing.JPanel();
        spSurveillantEpreuve = new javax.swing.JScrollPane();
        liSurveillantEpreuve = new javax.swing.JList<>();
        lNomSurveillant = new javax.swing.JLabel();
        cbSurveillanEpreuve = new javax.swing.JComboBox<>();
        btAjouter = new javax.swing.JButton();
        lUE = new javax.swing.JLabel();
        btImprimListEmargement = new javax.swing.JButton();
        cbChoixUe = new javax.swing.JComboBox<>();
        btImprimPvSurveillant = new javax.swing.JButton();
        btImprimPvIntero = new javax.swing.JButton();
        btImprimConvocEtud = new javax.swing.JButton();
        pEtudrepasUe = new javax.swing.JPanel();
        lPromo = new javax.swing.JLabel();
        cbChoixEtud = new javax.swing.JComboBox<>();
        lNomEtud = new javax.swing.JLabel();
        cbChoixEtudRepasUe = new javax.swing.JComboBox<>();
        btAjouterEtud = new javax.swing.JButton();
        btimprilConvocSurveil = new javax.swing.JButton();
        pInterogateurEpreuve = new javax.swing.JPanel();
        spListeInterogateur = new javax.swing.JScrollPane();
        liListeInterogateur = new javax.swing.JList<>();
        lNomInterogateur = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pGestionUsers = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemple d'utilisation des onglets");

        pGestionEtudiant.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 2, 12))); // NOI18N

        javax.swing.GroupLayout pAgendaLayout = new javax.swing.GroupLayout(pAgenda);
        pAgenda.setLayout(pAgendaLayout);
        pAgendaLayout.setHorizontalGroup(
            pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
        );
        pAgendaLayout.setVerticalGroup(
            pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );

        pGestionEtudiant.addTab("Agenda", pAgenda);

        pGestionEtudiants.setEnabled(false);

        jBGestionAbscence.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBGestionAbscence.setText("Gestion des abscences");

        jBGestionNote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBGestionNote.setText("Gestion des notes");

        btRestFichEtu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRestFichEtu.setText("restaurer la fiche d'un étudiant");

        btPassageEtuClasSup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPassageEtuClasSup.setText("Passage des étudiants en classe superieur");

        lTitreGestEtu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lTitreGestEtu.setText("                Gestion des étudiants");

        jBCreaSuprEtudiabnt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBCreaSuprEtudiabnt.setText("Création de la fiche d'un étudiant");
        jBCreaSuprEtudiabnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreaSuprEtudiabntActionPerformed(evt);
            }
        });

        jBModifEtudiant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBModifEtudiant.setText("Modification/supression de la fiche d'un étudiant");
        jBModifEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifEtudiantActionPerformed(evt);
            }
        });

        jBImporter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBImporter.setText("Importation à partir d'un fichier");

        javax.swing.GroupLayout pGestionEtudiantsLayout = new javax.swing.GroupLayout(pGestionEtudiants);
        pGestionEtudiants.setLayout(pGestionEtudiantsLayout);
        pGestionEtudiantsLayout.setHorizontalGroup(
            pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionEtudiantsLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPassageEtuClasSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGestionAbscence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lTitreGestEtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCreaSuprEtudiabnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBModifEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBImporter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGestionNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRestFichEtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(725, Short.MAX_VALUE))
        );
        pGestionEtudiantsLayout.setVerticalGroup(
            pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionEtudiantsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lTitreGestEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jBCreaSuprEtudiabnt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBModifEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRestFichEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBImporter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGestionAbscence, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGestionNote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPassageEtuClasSup, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(81, 81, 81))
        );

        pGestionEtudiant.addTab("gestion des étudiants", pGestionEtudiants);

        pGestionEnseignant.setEnabled(false);

        lTitreGestionEnseignants.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lTitreGestionEnseignants.setText("   Gestion des enseignants");

        btCreaSuprEtudiabnt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCreaSuprEtudiabnt1.setText("Création d'une fiche enseignant");

        jBModifEtudiant1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBModifEtudiant1.setText("Modification d'une fiche enseignants");
        jBModifEtudiant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifEtudiant1ActionPerformed(evt);
            }
        });

        jBImporter1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBImporter1.setText("Importation à partir d'un fichier");

        jBGestionNote1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBGestionNote1.setText("Gestion des cours faits");

        btCreationEtatHeure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCreationEtatHeure.setText("creation d'état des heures");

        javax.swing.GroupLayout pGestionEnseignantLayout = new javax.swing.GroupLayout(pGestionEnseignant);
        pGestionEnseignant.setLayout(pGestionEnseignantLayout);
        pGestionEnseignantLayout.setHorizontalGroup(
            pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
            .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lTitreGestionEnseignants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCreaSuprEtudiabnt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBModifEtudiant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBImporter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGestionNote1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCreationEtatHeure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(766, Short.MAX_VALUE)))
        );
        pGestionEnseignantLayout.setVerticalGroup(
            pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
            .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(lTitreGestionEnseignants, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)
                    .addComponent(btCreaSuprEtudiabnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jBModifEtudiant1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jBImporter1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jBGestionNote1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btCreationEtatHeure, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGap(101, 101, 101)))
        );

        pGestionEtudiant.addTab("Gestion des enseignants", pGestionEnseignant);

        pSurveillantEpreuve.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "surveillant de l'épreuve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        spSurveillantEpreuve.setViewportView(liSurveillantEpreuve);

        lNomSurveillant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomSurveillant.setText("Nom du surveillant");

        cbSurveillanEpreuve.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjouter.setText("Ajouter");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSurveillantEpreuveLayout = new javax.swing.GroupLayout(pSurveillantEpreuve);
        pSurveillantEpreuve.setLayout(pSurveillantEpreuveLayout);
        pSurveillantEpreuveLayout.setHorizontalGroup(
            pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(spSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                        .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                        .addComponent(lNomSurveillant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(cbSurveillanEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        pSurveillantEpreuveLayout.setVerticalGroup(
            pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomSurveillant, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSurveillanEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lUE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lUE.setText("U.E");

        btImprimListEmargement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimListEmargement.setText("imprimer liste d'emargement");

        btImprimPvSurveillant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimPvSurveillant.setText("imprimer Pv de surveillance");

        btImprimPvIntero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimPvIntero.setText("imprimer Pv d'interogation");

        btImprimConvocEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimConvocEtud.setText("Imprimer convocation étudiants");

        pEtudrepasUe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Etudiants devant repasser l'U.E.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lPromo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPromo.setText("promotion");

        cbChoixEtud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lNomEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomEtud.setText("nom de l'étudiant");

        cbChoixEtudRepasUe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAjouterEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjouterEtud.setText("Ajouter");

        javax.swing.GroupLayout pEtudrepasUeLayout = new javax.swing.GroupLayout(pEtudrepasUe);
        pEtudrepasUe.setLayout(pEtudrepasUeLayout);
        pEtudrepasUeLayout.setHorizontalGroup(
            pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEtudrepasUeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbChoixEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lNomEtud)
                .addGap(88, 88, 88)
                .addComponent(cbChoixEtudRepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(pEtudrepasUeLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(btAjouterEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pEtudrepasUeLayout.setVerticalGroup(
            pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEtudrepasUeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChoixEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNomEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChoixEtudRepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btAjouterEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        btimprilConvocSurveil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btimprilConvocSurveil.setText("Imprimer convocation surveillant");

        pInterogateurEpreuve.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "interrogateur pour l'épreuve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        liListeInterogateur.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spListeInterogateur.setViewportView(liListeInterogateur);

        lNomInterogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomInterogateur.setText("Nom de l'interogateur");

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Ajoute");

        javax.swing.GroupLayout pInterogateurEpreuveLayout = new javax.swing.GroupLayout(pInterogateurEpreuve);
        pInterogateurEpreuve.setLayout(pInterogateurEpreuveLayout);
        pInterogateurEpreuveLayout.setHorizontalGroup(
            pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInterogateurEpreuveLayout.createSequentialGroup()
                .addGroup(pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pInterogateurEpreuveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spListeInterogateur))
                    .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNomInterogateur)
                        .addGap(64, 64, 64)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        pInterogateurEpreuveLayout.setVerticalGroup(
            pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomInterogateur)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addGap(30, 30, 30)
                .addComponent(spListeInterogateur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Imprimer convocation interrogateur");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("gestion des examens");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("promotion");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nom", "prénom", "convoqué", "non convoqué"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout pGestionExamenLayout = new javax.swing.GroupLayout(pGestionExamen);
        pGestionExamen.setLayout(pGestionExamenLayout);
        pGestionExamenLayout.setHorizontalGroup(
            pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionExamenLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(592, Short.MAX_VALUE))
            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionExamenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(122, 122, 122)
                            .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(cbChoixUe, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(295, 295, 295)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pEtudrepasUe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pGestionExamenLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(pSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(pInterogateurEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(18, 18, 18)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btImprimConvocEtud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimListEmargement, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimPvSurveillant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btimprilConvocSurveil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimPvIntero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        pGestionExamenLayout.setVerticalGroup(
            pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionExamenLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionExamenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbChoixUe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(btImprimListEmargement, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(31, 31, 31)
                    .addComponent(btImprimConvocEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(pEtudrepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pInterogateurEpreuve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pSurveillantEpreuve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGestionExamenLayout.createSequentialGroup()
                            .addComponent(btimprilConvocSurveil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btImprimPvSurveillant, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btImprimPvIntero, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pGestionEtudiant.addTab("Gestion des examens", pGestionExamen);

        jTable1.setModel(userModel);
        jScrollPane4.setViewportView(jTable1);

        jButton5.setText("Ajouter");

        jButton11.setText("Supprmier");

        jButton12.setText("Modifier");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pGestionUsersLayout = new javax.swing.GroupLayout(pGestionUsers);
        pGestionUsers.setLayout(pGestionUsersLayout);
        pGestionUsersLayout.setHorizontalGroup(
            pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pGestionUsersLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        pGestionUsersLayout.setVerticalGroup(
            pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton12)
                    .addComponent(jButton11))
                .addContainerGap(510, Short.MAX_VALUE))
        );

        pGestionEtudiant.addTab("Gestion des users", pGestionUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pGestionEtudiant)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pGestionEtudiant)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCreaSuprEtudiabntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreaSuprEtudiabntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCreaSuprEtudiabntActionPerformed

    private void jBModifEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModifEtudiantActionPerformed

    private void jBModifEtudiant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifEtudiant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModifEtudiant1ActionPerformed

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAjouterActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btAjouterEtud;
    private javax.swing.JButton btCreaSuprEtudiabnt1;
    private javax.swing.JButton btCreationEtatHeure;
    private javax.swing.JButton btImprimConvocEtud;
    private javax.swing.JButton btImprimListEmargement;
    private javax.swing.JButton btImprimPvIntero;
    private javax.swing.JButton btImprimPvSurveillant;
    private javax.swing.JButton btPassageEtuClasSup;
    private javax.swing.JButton btRestFichEtu;
    private javax.swing.JButton btimprilConvocSurveil;
    private javax.swing.JComboBox<String> cbChoixEtud;
    private javax.swing.JComboBox<String> cbChoixEtudRepasUe;
    private javax.swing.JComboBox<String> cbChoixUe;
    private javax.swing.JComboBox<String> cbSurveillanEpreuve;
    private javax.swing.JButton jBCreaSuprEtudiabnt;
    private javax.swing.JButton jBGestionAbscence;
    private javax.swing.JButton jBGestionNote;
    private javax.swing.JButton jBGestionNote1;
    private javax.swing.JButton jBImporter;
    private javax.swing.JButton jBImporter1;
    private javax.swing.JButton jBModifEtudiant;
    private javax.swing.JButton jBModifEtudiant1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lNomEtud;
    private javax.swing.JLabel lNomInterogateur;
    private javax.swing.JLabel lNomSurveillant;
    private javax.swing.JLabel lPromo;
    private javax.swing.JLabel lTitreGestEtu;
    private javax.swing.JLabel lTitreGestionEnseignants;
    private javax.swing.JLabel lUE;
    private javax.swing.JList<String> liListeInterogateur;
    private javax.swing.JList<String> liSurveillantEpreuve;
    private javax.swing.JPanel pAgenda;
    private javax.swing.JPanel pEtudrepasUe;
    private javax.swing.JPanel pGestionEnseignant;
    private javax.swing.JTabbedPane pGestionEtudiant;
    private javax.swing.JPanel pGestionEtudiants;
    private javax.swing.JPanel pGestionExamen;
    private javax.swing.JPanel pGestionUsers;
    private javax.swing.JPanel pInterogateurEpreuve;
    private javax.swing.JPanel pSurveillantEpreuve;
    private javax.swing.JScrollPane spListeInterogateur;
    private javax.swing.JScrollPane spSurveillantEpreuve;
    // End of variables declaration//GEN-END:variables
}
