/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleReferentiel;
import appli.tools;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.User;

/**
 *
 * @author Mateusz
 */
public class FenetreAjoutModifUser extends javax.swing.JDialog {
    
    private boolean etatValidation;
    private User modUser;
    
    /**
     * 0 - ajout
     * 1 - suppresion
     * 2 - modification
     */
    private int action;
    public Connection cnx;

    /**
     * 
     * @param parent
     * @param user
     * @param userGroupes
     * @param libelle 
     */
    public FenetreAjoutModifUser(java.awt.Frame parent,
            User user,
            ModeleReferentiel userGroupes,
            int action,
            Connection cnx) {
        
        super(parent, true);
        initComponents();
        etatValidation = false;
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        this.modUser = user;
        this.action = action;
        this.cnx = cnx;
        this.lLibelle.setText(getLibelleAction(action));
        this.txLogin.setText(user.getLogin());
        this.txPrenomEtu1.setText(user.getFullname());
        this.cbUserGroupes.setModel(userGroupes);
        this.cbUserGroupes.setSelectedIndex(user.getGroupe()-1);
        
    }
    
    private String getLibelleAction(int a) {
        String ret = "";
        switch (a) {
            case 0: ret = "Ajouter un user"; break;
            case 1: ret = "Supprmier un user"; break;
            case 2: ret = "Modifier un user"; break;
            default: break;
        }
        
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNomEtu = new javax.swing.JLabel();
        txLogin = new javax.swing.JTextField();
        lPrenomEtu = new javax.swing.JLabel();
        lAdresse = new javax.swing.JLabel();
        cbUserGroupes = new javax.swing.JComboBox<>();
        lPrenomEtu1 = new javax.swing.JLabel();
        txPrenomEtu1 = new javax.swing.JTextField();
        lLibelle = new javax.swing.JLabel();
        txPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lNomEtu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomEtu.setText("Login");

        txLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lPrenomEtu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPrenomEtu.setText("Mot de passe");

        lAdresse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lAdresse.setText("Groupe");

        cbUserGroupes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lPrenomEtu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPrenomEtu1.setText("Nom et Prénom");

        txPrenomEtu1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lLibelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lLibelle.setText("libelle");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Sauvegarder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lNomEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(lPrenomEtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPrenomEtu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbUserGroupes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txLogin)
                        .addComponent(txPrenomEtu1)
                        .addComponent(lLibelle)
                        .addComponent(txPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lNomEtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lLibelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrenomEtu, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrenomEtu1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(txPrenomEtu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUserGroupes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        tools.debug("action: " + action);
        
        modUser.setLogin(txLogin.getText());
        modUser.setMotDePasse(String.valueOf(txPassword.getPassword()));
        modUser.setGroupe(cbUserGroupes.getSelectedIndex());
        
        int result;
        
        try {
        
           CallableStatement cstmt = cnx.prepareCall("begin GI_USER_SECURITY.add_user(?,?,?); end;");

           //cstmt.registerOutParameter (1, Types.INTEGER);

           cstmt.setString(1, modUser.getLogin());
           cstmt.setString(2, modUser.getMotDePasse());
           cstmt.setInt(3, modUser.getGroupe());

           cstmt.execute();

           tools.showDialog("Information", "Utilisateur " + modUser.getLogin()+ ""
                   + " a bien été ajouté");

           etatValidation = true;

           this.dispose();

       } catch (SQLException ex) { 
            Logger.getLogger(FenetreAjoutModifUser.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void addUser(User u) {
        
        
       
    }
    
    private void deleteUser() {
        
    }
    
    private void modifyUser() {
        
    }
    
    public User doModal() {
        this.setVisible(true);
        return modUser;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbUserGroupes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lAdresse;
    private javax.swing.JLabel lLibelle;
    private javax.swing.JLabel lNomEtu;
    private javax.swing.JLabel lPrenomEtu;
    private javax.swing.JLabel lPrenomEtu1;
    private javax.swing.JTextField txLogin;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txPrenomEtu1;
    // End of variables declaration//GEN-END:variables
}
