/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleUser;
import appli.tools;
import dao.DaoPromotion;
import dao.DaoUser;
import java.awt.Component;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import metier.Promotion;
import metier.User;

/**
 *
 * @author paul
 */
public class FenetreAcceuilPrincipal extends javax.swing.JFrame {
     
 Connection cnx;
    
    JFrame parent;
    public User currentUser;
    private ModeleUser userModel;
    private DaoUser dao;
    public Promotion promotion;
    
    /**
     * Creates new form Fenetre
     * @param cnx
     * @param u
     */
    public FenetreAcceuilPrincipal(Connection cnx, User u) throws SQLException {
        
        //init connection
        this.cnx = cnx;
        
        //init user
        this.currentUser = u;
        
        initComponents();
        
        //preparation affichage de la fenetre principale
        
        //affichage de la fenetre principale
            
            //je cherche la promotion qui est en cours
            DaoPromotion dp = new DaoPromotion(this.cnx);
            promotion = dp.getCurrentPromotion();
            this.lAnnee.setText("Promotion en cours: "+promotion.getNomPromotion());
            
            //activation des fenetres
            
            this.lLogin.setText("User login: "+u.getLogin());
            this.lNiveau.setText("Niveau: "+u.getGroupeLibelle());
            
            int[] activityTable = u.getOngletsGroupes();
            
            for (int i=0;i<=5;i++) {
                if (activityTable[i] == 1)
                    pGroupPane.setEnabledAt(i, true);
                else 
                    pGroupPane.setEnabledAt(i, false);
            }
        
        
        //this.l
        
        //pAccueil
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pGroupPane = new javax.swing.JTabbedPane();
        pAccueil = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        lNiveau = new javax.swing.JLabel();
        lAnnee = new javax.swing.JLabel();
        pAgenda = new javax.swing.JPanel();
        pGestionEtudiants = new javax.swing.JPanel();
        jBGestionAbscence = new javax.swing.JButton();
        jBGestionNote = new javax.swing.JButton();
        btRestFichEtu = new javax.swing.JButton();
        btPassageEtuClasSup = new javax.swing.JButton();
        lTitreGestEtu = new javax.swing.JLabel();
        jBCreaSuprEtudiabnt = new javax.swing.JButton();
        jBModifEtudiant = new javax.swing.JButton();
        jBImporter = new javax.swing.JButton();
        pGestionEnseignant = new javax.swing.JPanel();
        lTitreGestionEnseignants = new javax.swing.JLabel();
        btCreaSuprEtudiabnt1 = new javax.swing.JButton();
        jBModifEtudiant1 = new javax.swing.JButton();
        jBImporter1 = new javax.swing.JButton();
        jBGestionNote1 = new javax.swing.JButton();
        btCreationEtatHeure = new javax.swing.JButton();
        pGestionExamen = new javax.swing.JPanel();
        pSurveillantEpreuve = new javax.swing.JPanel();
        spSurveillantEpreuve = new javax.swing.JScrollPane();
        liSurveillantEpreuve = new javax.swing.JList<>();
        lNomSurveillant = new javax.swing.JLabel();
        cbSurveillanEpreuve = new javax.swing.JComboBox<>();
        btAjouter = new javax.swing.JButton();
        lUE = new javax.swing.JLabel();
        btImprimListEmargement = new javax.swing.JButton();
        cbChoixUe = new javax.swing.JComboBox<>();
        btImprimPvSurveillant = new javax.swing.JButton();
        btImprimPvIntero = new javax.swing.JButton();
        btImprimConvocEtud = new javax.swing.JButton();
        pEtudrepasUe = new javax.swing.JPanel();
        lPromo = new javax.swing.JLabel();
        cbChoixEtud = new javax.swing.JComboBox<>();
        lNomEtud = new javax.swing.JLabel();
        cbChoixEtudRepasUe = new javax.swing.JComboBox<>();
        btAjouterEtud = new javax.swing.JButton();
        btimprilConvocSurveil = new javax.swing.JButton();
        pInterogateurEpreuve = new javax.swing.JPanel();
        spListeInterogateur = new javax.swing.JScrollPane();
        liListeInterogateur = new javax.swing.JList<>();
        lNomInterogateur = new javax.swing.JLabel();
        cbChoixInterogateur = new javax.swing.JComboBox<>();
        btAjouterInterrogateur = new javax.swing.JButton();
        btImprimConvocIntrogateur = new javax.swing.JButton();
        tTitreGestionExam = new javax.swing.JLabel();
        lPromotion = new javax.swing.JLabel();
        cbChoixPromotion = new javax.swing.JComboBox<>();
        spListeEtudConvoque = new javax.swing.JScrollPane();
        tListeEtudConvoquer = new javax.swing.JTable();
        pGestionUsers = new javax.swing.JPanel();
        spUser = new javax.swing.JScrollPane();
        LiUser = new javax.swing.JTable();
        btAjouterUser = new javax.swing.JButton();
        btModifierUser = new javax.swing.JButton();
        btSuprimerUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemple d'utilisation des onglets");

        pGroupPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 2, 12))); // NOI18N
        pGroupPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pGroupPaneStateChanged(evt);
            }
        });
        pGroupPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pGroupPaneMouseClicked(evt);
            }
        });

        lLogin.setText("Login:");

        lNiveau.setText("Niveau:");

        lAnnee.setText("Année en cours: ");

        javax.swing.GroupLayout pAccueilLayout = new javax.swing.GroupLayout(pAccueil);
        pAccueil.setLayout(pAccueilLayout);
        pAccueilLayout.setHorizontalGroup(
            pAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLogin)
                    .addComponent(lNiveau)
                    .addComponent(lAnnee))
                .addContainerGap(1123, Short.MAX_VALUE))
        );
        pAccueilLayout.setVerticalGroup(
            pAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNiveau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAnnee)
                .addContainerGap(800, Short.MAX_VALUE))
        );

        pGroupPane.addTab("Accueil", pAccueil);

        javax.swing.GroupLayout pAgendaLayout = new javax.swing.GroupLayout(pAgenda);
        pAgenda.setLayout(pAgendaLayout);
        pAgendaLayout.setHorizontalGroup(
            pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
        );
        pAgendaLayout.setVerticalGroup(
            pAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );

        pGroupPane.addTab("Agenda", pAgenda);

        pGestionEtudiants.setEnabled(false);

        jBGestionAbscence.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBGestionAbscence.setText("Gestion des abscences");

        jBGestionNote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBGestionNote.setText("Gestion des notes");

        btRestFichEtu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRestFichEtu.setText("restaurer la fiche d'un étudiant");

        btPassageEtuClasSup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPassageEtuClasSup.setText("Passage des étudiants en classe superieur");

        lTitreGestEtu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lTitreGestEtu.setText("                Gestion des étudiants");

        jBCreaSuprEtudiabnt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBCreaSuprEtudiabnt.setText("Création de la fiche d'un étudiant");
        jBCreaSuprEtudiabnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreaSuprEtudiabntActionPerformed(evt);
            }
        });

        jBModifEtudiant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBModifEtudiant.setText("Modification/supression de la fiche d'un étudiant");
        jBModifEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifEtudiantActionPerformed(evt);
            }
        });

        jBImporter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBImporter.setText("Importation à partir d'un fichier");

        javax.swing.GroupLayout pGestionEtudiantsLayout = new javax.swing.GroupLayout(pGestionEtudiants);
        pGestionEtudiants.setLayout(pGestionEtudiantsLayout);
        pGestionEtudiantsLayout.setHorizontalGroup(
            pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionEtudiantsLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPassageEtuClasSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGestionAbscence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lTitreGestEtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCreaSuprEtudiabnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBModifEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBImporter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGestionNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRestFichEtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(725, Short.MAX_VALUE))
        );
        pGestionEtudiantsLayout.setVerticalGroup(
            pGestionEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionEtudiantsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lTitreGestEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jBCreaSuprEtudiabnt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBModifEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRestFichEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBImporter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGestionAbscence, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGestionNote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPassageEtuClasSup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        pGroupPane.addTab("Gestion des étudiants", pGestionEtudiants);

        pGestionEnseignant.setEnabled(false);

        lTitreGestionEnseignants.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lTitreGestionEnseignants.setText("   Gestion des enseignants");

        btCreaSuprEtudiabnt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCreaSuprEtudiabnt1.setText("Création d'une fiche enseignant");

        jBModifEtudiant1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBModifEtudiant1.setText("Modification d'une fiche enseignants");
        jBModifEtudiant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifEtudiant1ActionPerformed(evt);
            }
        });

        jBImporter1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBImporter1.setText("Importation à partir d'un fichier");

        jBGestionNote1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBGestionNote1.setText("Gestion des cours faits");

        btCreationEtatHeure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCreationEtatHeure.setText("creation d'état des heures");

        javax.swing.GroupLayout pGestionEnseignantLayout = new javax.swing.GroupLayout(pGestionEnseignant);
        pGestionEnseignant.setLayout(pGestionEnseignantLayout);
        pGestionEnseignantLayout.setHorizontalGroup(
            pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
            .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lTitreGestionEnseignants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCreaSuprEtudiabnt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBModifEtudiant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBImporter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGestionNote1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCreationEtatHeure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(766, Short.MAX_VALUE)))
        );
        pGestionEnseignantLayout.setVerticalGroup(
            pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
            .addGroup(pGestionEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionEnseignantLayout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(lTitreGestionEnseignants, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)
                    .addComponent(btCreaSuprEtudiabnt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jBModifEtudiant1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jBImporter1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jBGestionNote1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btCreationEtatHeure, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addGap(101, 101, 101)))
        );

        pGroupPane.addTab("Gestion des enseignants", pGestionEnseignant);

        pSurveillantEpreuve.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "surveillant de l'épreuve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        spSurveillantEpreuve.setViewportView(liSurveillantEpreuve);

        lNomSurveillant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomSurveillant.setText("Nom du surveillant");

        cbSurveillanEpreuve.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjouter.setText("Ajouter");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSurveillantEpreuveLayout = new javax.swing.GroupLayout(pSurveillantEpreuve);
        pSurveillantEpreuve.setLayout(pSurveillantEpreuveLayout);
        pSurveillantEpreuveLayout.setHorizontalGroup(
            pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(spSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                        .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pSurveillantEpreuveLayout.createSequentialGroup()
                        .addComponent(lNomSurveillant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(cbSurveillanEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        pSurveillantEpreuveLayout.setVerticalGroup(
            pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSurveillantEpreuveLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pSurveillantEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomSurveillant, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSurveillanEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lUE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lUE.setText("U.E");

        btImprimListEmargement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimListEmargement.setText("imprimer liste d'emargement");

        btImprimPvSurveillant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimPvSurveillant.setText("imprimer Pv de surveillance");

        btImprimPvIntero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimPvIntero.setText("imprimer Pv d'interogation");

        btImprimConvocEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimConvocEtud.setText("Imprimer convocation étudiants");

        pEtudrepasUe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Etudiants devant repasser l'U.E.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lPromo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPromo.setText("promotion");

        cbChoixEtud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lNomEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomEtud.setText("nom de l'étudiant");

        cbChoixEtudRepasUe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAjouterEtud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjouterEtud.setText("Ajouter");

        javax.swing.GroupLayout pEtudrepasUeLayout = new javax.swing.GroupLayout(pEtudrepasUe);
        pEtudrepasUe.setLayout(pEtudrepasUeLayout);
        pEtudrepasUeLayout.setHorizontalGroup(
            pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEtudrepasUeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbChoixEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lNomEtud)
                .addGap(88, 88, 88)
                .addComponent(cbChoixEtudRepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(pEtudrepasUeLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(btAjouterEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pEtudrepasUeLayout.setVerticalGroup(
            pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEtudrepasUeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pEtudrepasUeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChoixEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNomEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChoixEtudRepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btAjouterEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        btimprilConvocSurveil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btimprilConvocSurveil.setText("Imprimer convocation surveillant");

        pInterogateurEpreuve.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "interrogateur pour l'épreuve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        liListeInterogateur.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spListeInterogateur.setViewportView(liListeInterogateur);

        lNomInterogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNomInterogateur.setText("Nom de l'interogateur");

        cbChoixInterogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbChoixInterogateur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAjouterInterrogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjouterInterrogateur.setText("Ajoute");

        javax.swing.GroupLayout pInterogateurEpreuveLayout = new javax.swing.GroupLayout(pInterogateurEpreuve);
        pInterogateurEpreuve.setLayout(pInterogateurEpreuveLayout);
        pInterogateurEpreuveLayout.setHorizontalGroup(
            pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btAjouterInterrogateur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInterogateurEpreuveLayout.createSequentialGroup()
                .addGroup(pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pInterogateurEpreuveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spListeInterogateur))
                    .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNomInterogateur)
                        .addGap(64, 64, 64)
                        .addComponent(cbChoixInterogateur, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        pInterogateurEpreuveLayout.setVerticalGroup(
            pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInterogateurEpreuveLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pInterogateurEpreuveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomInterogateur)
                    .addComponent(cbChoixInterogateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btAjouterInterrogateur)
                .addGap(30, 30, 30)
                .addComponent(spListeInterogateur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btImprimConvocIntrogateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImprimConvocIntrogateur.setText("Imprimer convocation interrogateur");

        tTitreGestionExam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tTitreGestionExam.setText("gestion des examens");

        lPromotion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPromotion.setText("promotion");

        cbChoixPromotion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tListeEtudConvoquer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nom", "prénom", "convoqué", "non convoqué"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spListeEtudConvoque.setViewportView(tListeEtudConvoquer);

        javax.swing.GroupLayout pGestionExamenLayout = new javax.swing.GroupLayout(pGestionExamen);
        pGestionExamen.setLayout(pGestionExamenLayout);
        pGestionExamenLayout.setHorizontalGroup(
            pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionExamenLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(spListeEtudConvoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(592, Short.MAX_VALUE))
            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionExamenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addComponent(lPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(cbChoixPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(122, 122, 122)
                            .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(cbChoixUe, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(295, 295, 295)
                            .addComponent(tTitreGestionExam, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pEtudrepasUe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pGestionExamenLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(pSurveillantEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(pInterogateurEpreuve, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(18, 18, 18)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btImprimConvocEtud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimListEmargement, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btImprimConvocIntrogateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimPvSurveillant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btimprilConvocSurveil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btImprimPvIntero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        pGestionExamenLayout.setVerticalGroup(
            pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionExamenLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(spListeEtudConvoque, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pGestionExamenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tTitreGestionExam, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbChoixPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbChoixUe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lUE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pGestionExamenLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(btImprimListEmargement, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(31, 31, 31)
                    .addComponent(btImprimConvocEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(pEtudrepasUe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addGroup(pGestionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pInterogateurEpreuve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pSurveillantEpreuve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGestionExamenLayout.createSequentialGroup()
                            .addComponent(btimprilConvocSurveil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btImprimPvSurveillant, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btImprimConvocIntrogateur, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btImprimPvIntero, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pGroupPane.addTab("Gestion des examens", pGestionExamen);

        pGestionUsers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                showUsers(evt);
            }
        });
        pGestionUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pGestionUsersMouseClicked(evt);
            }
        });

        spUser.setViewportView(LiUser);

        btAjouterUser.setText("Ajouter");

        btModifierUser.setText("Supprmier");

        btSuprimerUser.setText("Modifier");
        btSuprimerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuprimerUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pGestionUsersLayout = new javax.swing.GroupLayout(pGestionUsers);
        pGestionUsers.setLayout(pGestionUsersLayout);
        pGestionUsersLayout.setHorizontalGroup(
            pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spUser, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pGestionUsersLayout.createSequentialGroup()
                        .addComponent(btAjouterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSuprimerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btModifierUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        pGestionUsersLayout.setVerticalGroup(
            pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spUser, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGestionUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjouterUser)
                    .addComponent(btSuprimerUser)
                    .addComponent(btModifierUser))
                .addContainerGap(532, Short.MAX_VALUE))
        );

        pGroupPane.addTab("Gestion des users", pGestionUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pGroupPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pGroupPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCreaSuprEtudiabntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreaSuprEtudiabntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCreaSuprEtudiabntActionPerformed

    private void jBModifEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModifEtudiantActionPerformed

    private void jBModifEtudiant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifEtudiant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModifEtudiant1ActionPerformed

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAjouterActionPerformed

    private void btSuprimerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuprimerUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSuprimerUserActionPerformed

    private void showUsers(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_showUsers
    }//GEN-LAST:event_showUsers

    private void pGestionUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGestionUsersMouseClicked
    }//GEN-LAST:event_pGestionUsersMouseClicked

    private void pGroupPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGroupPaneMouseClicked
        
        //actions supplementaires on clicque
        
        
    }//GEN-LAST:event_pGroupPaneMouseClicked

    private void pGroupPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pGroupPaneStateChanged
        
        //TODO: juste pour le periode de dev, apres il faut mettre toutes les
        // pane's dans ce propres classes
        
        JTabbedPane sourceTabbedPane = (JTabbedPane)evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();
        
        //onglet users
        if (index == 5) {
            tools.debug("->GestionUsers");
            
            //init de dao pour recuperation des données
            dao = new DaoUser(cnx);
            
            //recuperation des données
            userModel = new ModeleUser(dao);
            
            //je met le model dans la table
            LiUser.setModel(userModel);
            
        } else if (index == 3) {
            //onglet enseignant
            
            //TODO: Paul mettre model + dao d'ensegeignant
        }
            
    }//GEN-LAST:event_pGroupPaneStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LiUser;
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btAjouterEtud;
    private javax.swing.JButton btAjouterInterrogateur;
    private javax.swing.JButton btAjouterUser;
    private javax.swing.JButton btCreaSuprEtudiabnt1;
    private javax.swing.JButton btCreationEtatHeure;
    private javax.swing.JButton btImprimConvocEtud;
    private javax.swing.JButton btImprimConvocIntrogateur;
    private javax.swing.JButton btImprimListEmargement;
    private javax.swing.JButton btImprimPvIntero;
    private javax.swing.JButton btImprimPvSurveillant;
    private javax.swing.JButton btModifierUser;
    private javax.swing.JButton btPassageEtuClasSup;
    private javax.swing.JButton btRestFichEtu;
    private javax.swing.JButton btSuprimerUser;
    private javax.swing.JButton btimprilConvocSurveil;
    private javax.swing.JComboBox<String> cbChoixEtud;
    private javax.swing.JComboBox<String> cbChoixEtudRepasUe;
    private javax.swing.JComboBox<String> cbChoixInterogateur;
    private javax.swing.JComboBox<String> cbChoixPromotion;
    private javax.swing.JComboBox<String> cbChoixUe;
    private javax.swing.JComboBox<String> cbSurveillanEpreuve;
    private javax.swing.JButton jBCreaSuprEtudiabnt;
    private javax.swing.JButton jBGestionAbscence;
    private javax.swing.JButton jBGestionNote;
    private javax.swing.JButton jBGestionNote1;
    private javax.swing.JButton jBImporter;
    private javax.swing.JButton jBImporter1;
    private javax.swing.JButton jBModifEtudiant;
    private javax.swing.JButton jBModifEtudiant1;
    private javax.swing.JLabel lAnnee;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lNiveau;
    private javax.swing.JLabel lNomEtud;
    private javax.swing.JLabel lNomInterogateur;
    private javax.swing.JLabel lNomSurveillant;
    private javax.swing.JLabel lPromo;
    private javax.swing.JLabel lPromotion;
    private javax.swing.JLabel lTitreGestEtu;
    private javax.swing.JLabel lTitreGestionEnseignants;
    private javax.swing.JLabel lUE;
    private javax.swing.JList<String> liListeInterogateur;
    private javax.swing.JList<String> liSurveillantEpreuve;
    private javax.swing.JPanel pAccueil;
    private javax.swing.JPanel pAgenda;
    private javax.swing.JPanel pEtudrepasUe;
    private javax.swing.JPanel pGestionEnseignant;
    private javax.swing.JPanel pGestionEtudiants;
    private javax.swing.JPanel pGestionExamen;
    private javax.swing.JPanel pGestionUsers;
    private javax.swing.JTabbedPane pGroupPane;
    private javax.swing.JPanel pInterogateurEpreuve;
    private javax.swing.JPanel pSurveillantEpreuve;
    private javax.swing.JScrollPane spListeEtudConvoque;
    private javax.swing.JScrollPane spListeInterogateur;
    private javax.swing.JScrollPane spSurveillantEpreuve;
    private javax.swing.JScrollPane spUser;
    private javax.swing.JTable tListeEtudConvoquer;
    private javax.swing.JLabel tTitreGestionExam;
    // End of variables declaration//GEN-END:variables
}
