/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleListeClasse;
import appli.tools;
import dao.DaoClasse;
import java.awt.Frame;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Classe;

/**
 *
 * @author Mateusz
 */
public class PanelClasse extends javax.swing.JPanel {
    
    Connection cnx;
    DaoClasse leDao;
    ModeleListeClasse ml;
    
    Frame myparent;

    /**
     * Creates new form PanelClasse
     * @param c
     */
    public PanelClasse(Connection c, Frame parent) {
        initComponents();
        
        this.setName("Gestion Classes");
        
        cnx = c;
        leDao = new DaoClasse(cnx);
        myparent = parent;
        
        ml = new ModeleListeClasse(leDao);
        
        liListeClasse.setModel(ml);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        liListeClasse = new javax.swing.JTable();
        btAjout = new javax.swing.JButton();
        btSuppression = new javax.swing.JButton();

        liListeClasse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(liListeClasse);

        btAjout.setText("Ajout Classe");
        btAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjoutActionPerformed(evt);
            }
        });

        btSuppression.setText("Delete Classe");
        btSuppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuppressionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAjout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSuppression)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjout)
                    .addComponent(btSuppression))
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjoutActionPerformed
       
        //Classe c = ml.get(liListeClasse.getSelectedRow());
        Classe c = new Classe();
        
        FenetreAjoutModifClasse f = new FenetreAjoutModifClasse(myparent, c, cnx);
        c = f.doModal();
        
        if (c.getIdClasse() != 0) {
            tools.debug(c.toString());
            ml.insererLigne(c);
        }
        
    }//GEN-LAST:event_btAjoutActionPerformed

    private void btSuppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuppressionActionPerformed
        
        if (liListeClasse.getSelectedRow() != -1) {
        
            try {

            //are you sure ?
            //if ()
            int result;
            Classe current = this.ml.get(liListeClasse.getSelectedRow());
            int id_suppression = current.getIdClasse();

            CallableStatement cstmt = cnx.prepareCall ("{ ? = call SUPPRIMER_CLASSE(?)}");

            cstmt.registerOutParameter (1, Types.INTEGER);
            cstmt.setInt(2, id_suppression);
            cstmt.execute();
            result = cstmt.getInt(1);

            tools.debug("Suppresion : " + result);

            if (result == 1) {
                        //todo implementer methode modifier
                JOptionPane.showMessageDialog(null, "Classe "
                    +current.getNom() + " a été bien supprimé",
                    "Information", JOptionPane.INFORMATION_MESSAGE);

                this.ml.supprimerLigne(liListeClasse.getSelectedRow());

            } else {
                //result != 1
                throw new Exception("Impossible de supprimer ens");
            }

            } catch (SQLException ex) {
                Logger.getLogger(FenetreModifEnseignant.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FenetreModifEnseignant.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selectionner un ligne svp","Message", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btSuppressionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjout;
    private javax.swing.JButton btSuppression;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable liListeClasse;
    // End of variables declaration//GEN-END:variables
}
