/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleClasse;
import appli.ModeleListeClasse;
import appli.ModeleListeGroupe;
import appli.tools;
import dao.DaoClasse;
import dao.DaoGroupe;
import java.awt.Frame;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Classe;
import metier.Groupe;
import metier.Promotion;
import static oracle.net.aso.b.c;

/**
 *
 * @author Mateusz
 */
public class PanelGroupes extends javax.swing.JPanel {
    
    Connection cnx;
    DaoClasse leDao;
    public DaoGroupe leDaoGroupe;
    public ModeleClasse mc;
    ModeleListeGroupe mg;
    Promotion currentPromo;
    
    Frame myparent;

    /**
     * Creates new form PanelClasse
     * @param c
     * @param parent
     * @param promo
     */
    public PanelGroupes(Connection c, Frame parent, Promotion promo) {
        
        initComponents();
        
        this.setName("Gestion des groupes");
        
        cnx = c;
        currentPromo = promo;
        myparent = parent;
        
        //daos
        leDao = new DaoClasse(cnx);
        leDaoGroupe = new DaoGroupe(cnx);
        
        //models
        mc = new ModeleClasse(leDao);
        cbClasses.setModel(mc);
        //cbClasses.setSelectedIndex(1);
        
        //int idclasse = mc.get(cbClasses.getSelectedIndex()).getIdClasse();
        int idclasse = 1;
        
        tools.debug("id_classe: " + idclasse);
        
        mg = new ModeleListeGroupe(leDaoGroupe,currentPromo.getAnnée(),idclasse);
        
        liListeGroupes.setModel(mg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        liListeGroupes = new javax.swing.JTable();
        btAjout = new javax.swing.JButton();
        btSuppression = new javax.swing.JButton();
        lClass = new javax.swing.JLabel();
        cbClasses = new javax.swing.JComboBox<>();

        liListeGroupes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        liListeGroupes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(liListeGroupes);

        btAjout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAjout.setText("Ajouter un  groupe");
        btAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjoutActionPerformed(evt);
            }
        });

        btSuppression.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuppression.setText("Supprimer un groupe");
        btSuppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuppressionActionPerformed(evt);
            }
        });

        lClass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lClass.setText("Classe");

        cbClasses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbClasses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClassesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lClass)
                                .addGap(27, 27, 27)
                                .addComponent(cbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSuppression, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lClass)
                    .addComponent(cbClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuppression, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjoutActionPerformed
       
        //Classe c = ml.get(liListeClasse.getSelectedRow());
        Groupe g = new Groupe();
        
        Classe c = mc.get(cbClasses.getSelectedIndex());
        
        tools.debug(c.toString());
        
        g.setIdClasse(c.getIdClasse());
        g.setNomClasse(c.getNom());
        
        FenetreAjoutModifGroupe f = new FenetreAjoutModifGroupe(myparent, g, cnx);
        g = f.doModal();
        
        if (g.getIdGroupe() != 0) {
            
            g.setClassFullname(currentPromo.getNomPromotion()+ " " + c.getNom());
            
            tools.debug(g.toString());
            mg.insererLigne(g);
        }
        
    }//GEN-LAST:event_btAjoutActionPerformed

    private void btSuppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuppressionActionPerformed
        
        if (liListeGroupes.getSelectedRow() != -1) {
        
            try {

            //are you sure ?
            //if ()
            int result;
            Groupe current = this.mg.get(liListeGroupes.getSelectedRow());
            int id_suppression = current.getIdGroupe();

            CallableStatement cstmt = cnx.prepareCall ("{ ? = call SUPPRIMER_GROUPE(?)}");

            cstmt.registerOutParameter (1, Types.INTEGER);
            cstmt.setInt(2, id_suppression);
            cstmt.execute();
            result = cstmt.getInt(1);

            tools.debug("Suppresion : " + result);

            if (result == 1) {
                        //todo implementer methode modifier
                JOptionPane.showMessageDialog(null, "Groupe "
                    +current.getNom() + " a été bien supprimé",
                    "Information", JOptionPane.INFORMATION_MESSAGE);

                this.mg.supprimerLigne(liListeGroupes.getSelectedRow());

            } else {
                //result != 1
                throw new Exception("Impossible de supprimer la groupe");
            }

            } catch (SQLException ex) {
                Logger.getLogger(FenetreModifEnseignant.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FenetreModifEnseignant.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selectionner un ligne svp","Message", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btSuppressionActionPerformed

    private void cbClassesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClassesItemStateChanged
        
        if (cbClasses.getSelectedIndex() != -1) {
            
            //recharge models
            mg.classe = mc.get(cbClasses.getSelectedIndex()).getIdClasse();

            try {
                mg.charger();
                mg.fireTableDataChanged();
            } catch (SQLException ex) {
                Logger.getLogger(PanelGroupes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_cbClassesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjout;
    private javax.swing.JButton btSuppression;
    private javax.swing.JComboBox<String> cbClasses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lClass;
    private javax.swing.JTable liListeGroupes;
    // End of variables declaration//GEN-END:variables
}
