/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import appli.ModeleClasse;
import appli.ModeleListeGroupe;
import appli.ModeleListeSalle;
import appli.tools;
import dao.DaoClasse;
import dao.DaoGroupe;
import dao.DaoSalle;
import java.awt.Frame;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Classe;
import metier.Groupe;
import metier.Promotion;
import metier.Salle;
import static oracle.net.aso.b.c;

/**
 *
 * @author Mateusz
 */
public class PanelSalle extends javax.swing.JPanel {
    
    Connection cnx;
    DaoSalle leDao;
    ModeleListeSalle ms;
    
    Frame myparent;

    /**
     * Creates new form PanelClasse
     * @param c
     * @param parent
     * @param promo
     */
    public PanelSalle(Connection c, Frame parent) {
        
        initComponents();
        
        this.setName("Gestion des salles");
        
        cnx = c;
        myparent = parent;
        
        //daos
        leDao = new DaoSalle(cnx);
        
        //models
        ms = new ModeleListeSalle(leDao);
        
        liListeSalle.setModel(ms);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        liListeSalle = new javax.swing.JTable();
        btAjout = new javax.swing.JButton();
        btSuppression = new javax.swing.JButton();

        liListeSalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(liListeSalle);

        btAjout.setText("Ajout Salle");
        btAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjoutActionPerformed(evt);
            }
        });

        btSuppression.setText("Supprimmer salle");
        btSuppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuppressionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAjout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSuppression)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjout)
                    .addComponent(btSuppression))
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjoutActionPerformed
       
        //Salle s = ms.get(liListeSalle.getSelectedRow());
        Salle s = new Salle();
        
        FenetreAjoutModifSalle f = new FenetreAjoutModifSalle(myparent, s, cnx);
        s = f.doModal();
        
        if (s.getIdSalle() != 0) {
            
            ms.insererLigne(s);
        }
        
    }//GEN-LAST:event_btAjoutActionPerformed

    private void btSuppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuppressionActionPerformed
        
        if (liListeSalle.getSelectedRow() != -1) {
        
            try {

            //are you sure ?
            //if ()
            int result;
            Salle current = this.ms.get(liListeSalle.getSelectedRow());
            int id_suppression = current.getIdSalle();

            CallableStatement cstmt = cnx.prepareCall ("{ ? = call SUPPRIMER_SALLE(?)}");

            cstmt.registerOutParameter (1, Types.INTEGER);
            cstmt.setInt(2, id_suppression);
            cstmt.execute();
            result = cstmt.getInt(1);

            tools.debug("Suppresion : " + result);

            if (result == 1) {
                        //todo implementer methode modifier
                JOptionPane.showMessageDialog(null, "Salle "
                    +current.getNomSalle()+ " a été bien supprimé",
                    "Information", JOptionPane.INFORMATION_MESSAGE);

                this.ms.supprimerLigne(liListeSalle.getSelectedRow());

            } else {
                //result != 1
                throw new Exception("Impossible de supprimer la groupe");
            }

            } catch (SQLException ex) {
                Logger.getLogger(FenetreModifEnseignant.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FenetreModifEnseignant.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selectionner un ligne svp","Message", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btSuppressionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjout;
    private javax.swing.JButton btSuppression;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable liListeSalle;
    // End of variables declaration//GEN-END:variables
}
